/*************************************************************/
/* Copyright (C) 2021 OSS Nokalva, Inc.  All rights reserved.*/
/*************************************************************/

/* THIS FILE IS PROPRIETARY MATERIAL OF OSS NOKALVA, INC.
 * AND MAY BE USED ONLY BY DIRECT LICENSEES OF OSS NOKALVA, INC.
 * THIS FILE MAY NOT BE DISTRIBUTED.
 * THIS COPYRIGHT STATEMENT MAY NOT BE REMOVED. */

/* This file was generated by a TRIAL version of the OSS ASN.1 Tools.
 * Applications built using this file can be executed only on the machine
 * on which you run the OSS ASN.1 compiler. */

/* Generated for: dasdas (Trial), License 84426Z 84426Z. */
/* Abstract syntax: kekeo_asn1 */
/* Created: Wed Dec 15 21:28:41 2021 */
/* ASN.1 compiler version: 11.1 */
/* Code generated for runtime version 11.1 or later */
/* Compiler operating system: Windows */
/* Compiler machine type: Intel x86 */
/* Target operating system: Windows */
/* Target machine type: Intel x86 */
/* C compiler options required: -Zp4 (Microsoft) */
/* ASN.1 compiler options and file names specified:
 * -controlfile kull_m_kerberos_oss_asn1_internal_Win32.c -headerfile
 * kull_m_kerberos_oss_asn1_internal.h -prefix KULL_M_ASN1_ -externalname
 * kekeo_asn1 -verbose -der -root -noSampleCode -messageFormat msvc
 * -cstylecomments -allow universaltags
 * D:\Program Files (x86)\OSS Nokalva\ossasn1\win32.trial\11.1.0\asn1dflt\asn1dflt.ms.zp4
 * KerberosV5Spec2.asn KerberosV5-PK-INIT-SPEC.asn PKIX1Explicit88.asn
 * PKINIT.asn MS-SFU-KILE.asn
 */

#define    OSS_COMPILER_API_LEVEL 41
#define    _OSS_CONTROL_FILE
#define    OSS_SOED_BER
#include   "osstype.h"
#include   "kull_m_kerberos_oss_asn1_internal.h"

static unsigned char _v0[] = { 0x2B, 0x06, 0x01, 0x05, 0x02 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_krb5 = {
    5,
    _v0
};

static unsigned char _v1[] = { 0x2B, 0x06, 0x01, 0x05, 0x02, 0x03 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_pkinit = {
    6,
    _v1
};

static unsigned char _v2[] = { 0x2B, 0x06, 0x01, 0x05, 0x02, 0x03, 0x01 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_pkinit_authData = {
    7,
    _v2
};

static unsigned char _v3[] = { 0x2B, 0x06, 0x01, 0x05, 0x02, 0x03, 0x02 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_pkinit_DHKeyData = {
    7,
    _v3
};

static unsigned char _v4[] = { 0x2B, 0x06, 0x01, 0x05, 0x02, 0x03, 0x03 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_pkinit_rkeyData = {
    7,
    _v4
};

static unsigned char _v5[] = { 0x2B, 0x06, 0x01, 0x05, 0x02, 0x03, 0x04 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_pkinit_KPClientAuth = {
    7,
    _v5
};

static unsigned char _v6[] = { 0x2B, 0x06, 0x01, 0x05, 0x02, 0x03, 0x05 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_pkinit_KPKdc = {
    7,
    _v6
};

static unsigned char _v7[] = { 0x2B, 0x06, 0x01, 0x05, 0x02, 0x02 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_pkinit_san = {
    6,
    _v7
};

const int KULL_M_ASN1_pa_pk_as_req = 16;

const int KULL_M_ASN1_pa_pk_as_rep = 17;

const int KULL_M_ASN1_ad_initial_verified_cas = 9;

const int KULL_M_ASN1_td_trusted_certifiers = 104;

const int KULL_M_ASN1_td_invalid_certificates = 105;

const int KULL_M_ASN1_td_dh_parameters = 109;

static unsigned char _v8[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_pkix = {
    6,
    _v8
};

static unsigned char _v9[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x01 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_pe = {
    7,
    _v9
};

static unsigned char _v10[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x02 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_qt = {
    7,
    _v10
};

static unsigned char _v11[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x03 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_kp = {
    7,
    _v11
};

static unsigned char _v12[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x30 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_ad = {
    7,
    _v12
};

static unsigned char _v13[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x02, 0x01 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_qt_cps = {
    8,
    _v13
};

static unsigned char _v14[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x02, 0x02 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_qt_unotice = {
    8,
    _v14
};

static unsigned char _v15[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x30, 0x01 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_ad_ocsp = {
    8,
    _v15
};

static unsigned char _v16[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x30, 0x02 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_ad_caIssuers = {
    8,
    _v16
};

static unsigned char _v17[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x30, 0x03 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_ad_timeStamping = {
    8,
    _v17
};

static unsigned char _v18[] = { 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x30, 0x05 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_ad_caRepository = {
    8,
    _v18
};

static unsigned char _v19[] = { 0x55, 0x04 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_id_at = {
    2,
    _v19
};

static unsigned char _v20[] = { 0x55, 0x04, 0x29 };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_name = {
    3,
    _v20
};

static unsigned char _v21[] = { 0x55, 0x04, 0x04 };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_surname = {
    3,
    _v21
};

static unsigned char _v22[] = { 0x55, 0x04, 0x2A };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_givenName = {
    3,
    _v22
};

static unsigned char _v23[] = { 0x55, 0x04, 0x2B };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_initials = {
    3,
    _v23
};

static unsigned char _v24[] = { 0x55, 0x04, 0x2C };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_generationQualifier = {
    3,
    _v24
};

static unsigned char _v25[] = { 0x55, 0x04, 0x03 };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_commonName = {
    3,
    _v25
};

static unsigned char _v26[] = { 0x55, 0x04, 0x07 };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_localityName = {
    3,
    _v26
};

static unsigned char _v27[] = { 0x55, 0x04, 0x08 };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_stateOrProvinceName = {
    3,
    _v27
};

static unsigned char _v28[] = { 0x55, 0x04, 0x0A };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_organizationName = {
    3,
    _v28
};

static unsigned char _v29[] = { 0x55, 0x04, 0x0B };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_organizationalUnitName = {
    3,
    _v29
};

static unsigned char _v30[] = { 0x55, 0x04, 0x0C };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_title = {
    3,
    _v30
};

static unsigned char _v31[] = { 0x55, 0x04, 0x2E };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_dnQualifier = {
    3,
    _v31
};

static unsigned char _v32[] = { 0x55, 0x04, 0x06 };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_countryName = {
    3,
    _v32
};

static unsigned char _v33[] = { 0x55, 0x04, 0x05 };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_serialNumber = {
    3,
    _v33
};

static unsigned char _v34[] = { 0x55, 0x04, 0x41 };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_at_pseudonym = {
    3,
    _v34
};

static unsigned char _v35[] = { 0x09, 0x92, 0x26, 0x89, 0x93, 0xF2, 0x2C, 0x64, 0x01, 0x19 };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_domainComponent = {
    10,
    _v35
};

static unsigned char _v36[] = { 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x09 };
KULL_M_ASN1__ObjectID KULL_M_ASN1_pkcs_9 = {
    8,
    _v36
};

static unsigned char _v37[] = { 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x09, 0x01 };
KULL_M_ASN1_AttributeType KULL_M_ASN1_id_emailAddress = {
    9,
    _v37
};

const int KULL_M_ASN1_common_name = 1;

const int KULL_M_ASN1_teletex_common_name = 2;

const int KULL_M_ASN1_teletex_organization_name = 3;

const int KULL_M_ASN1_teletex_personal_name = 4;

const int KULL_M_ASN1_teletex_organizational_unit_names = 5;

const int KULL_M_ASN1_pds_name = 7;

const int KULL_M_ASN1_physical_delivery_country_name = 8;

const int KULL_M_ASN1_postal_code = 9;

const int KULL_M_ASN1_physical_delivery_office_name = 10;

const int KULL_M_ASN1_physical_delivery_office_number = 11;

const int KULL_M_ASN1_extension_OR_address_components = 12;

const int KULL_M_ASN1_physical_delivery_personal_name = 13;

const int KULL_M_ASN1_physical_delivery_organization_name = 14;

const int KULL_M_ASN1_extension_physical_delivery_address_components = 15;

const int KULL_M_ASN1_unformatted_postal_address = 16;

const int KULL_M_ASN1_street_address = 17;

const int KULL_M_ASN1_post_office_box_address = 18;

const int KULL_M_ASN1_poste_restante_address = 19;

const int KULL_M_ASN1_unique_postal_name = 20;

const int KULL_M_ASN1_local_postal_attributes = 21;

const int KULL_M_ASN1_extended_network_address = 22;

const int KULL_M_ASN1_terminal_type = 23;

const int KULL_M_ASN1_teletex_domain_defined_attributes = 6;

const int KULL_M_ASN1_ub_name = 32768;

const int KULL_M_ASN1_ub_common_name = 64;

const int KULL_M_ASN1_ub_locality_name = 128;

const int KULL_M_ASN1_ub_state_name = 128;

const int KULL_M_ASN1_ub_organization_name = 64;

const int KULL_M_ASN1_ub_organizational_unit_name = 64;

const int KULL_M_ASN1_ub_title = 64;

const int KULL_M_ASN1_ub_serial_number = 64;

const int KULL_M_ASN1_ub_match = 128;

const int KULL_M_ASN1_ub_emailaddress_length = 128;

const int KULL_M_ASN1_ub_common_name_length = 64;

const int KULL_M_ASN1_ub_country_name_alpha_length = 2;

const int KULL_M_ASN1_ub_country_name_numeric_length = 3;

const int KULL_M_ASN1_ub_domain_defined_attributes = 4;

const int KULL_M_ASN1_ub_domain_defined_attribute_type_length = 8;

const int KULL_M_ASN1_ub_domain_defined_attribute_value_length = 128;

const int KULL_M_ASN1_ub_domain_name_length = 16;

const int KULL_M_ASN1_ub_extension_attributes = 256;

const int KULL_M_ASN1_ub_e163_4_number_length = 15;

const int KULL_M_ASN1_ub_e163_4_sub_address_length = 40;

const int KULL_M_ASN1_ub_generation_qualifier_length = 3;

const int KULL_M_ASN1_ub_given_name_length = 16;

const int KULL_M_ASN1_ub_initials_length = 5;

const int KULL_M_ASN1_ub_integer_options = 256;

const int KULL_M_ASN1_ub_numeric_user_id_length = 32;

const int KULL_M_ASN1_ub_organization_name_length = 64;

const int KULL_M_ASN1_ub_organizational_unit_name_length = 32;

const int KULL_M_ASN1_ub_organizational_units = 4;

const int KULL_M_ASN1_ub_pds_name_length = 16;

const int KULL_M_ASN1_ub_pds_parameter_length = 30;

const int KULL_M_ASN1_ub_pds_physical_address_lines = 6;

const int KULL_M_ASN1_ub_postal_code_length = 16;

const int KULL_M_ASN1_ub_pseudonym = 128;

const int KULL_M_ASN1_ub_surname_length = 40;

const int KULL_M_ASN1_ub_terminal_id_length = 24;

const int KULL_M_ASN1_ub_unformatted_address_length = 180;

const int KULL_M_ASN1_ub_x121_address_length = 16;

static ossBoolean _v38 = FALSE;

static int _v39 = 0;

static unsigned short _v40 = 30;

static unsigned short _v41 = 5;

static unsigned short _v42 = 22;

static unsigned short _v43 = 5;

static unsigned short _v44 = 21;

static unsigned short _v45 = 5;

static unsigned short _v46 = 20;

static unsigned short _v47 = 5;

static unsigned short _v48 = 15;

static unsigned short _v49 = 5;

static unsigned short _v50 = 5;

static unsigned short _v51 = 14;

static unsigned short _v52 = 5;

static unsigned short _v53 = 11;

static unsigned short _v54 = 13;

static unsigned short _v55 = 5;

static unsigned short _v56 = 10;

static unsigned short _v57 = 12;

static unsigned short _v58 = 5;

static unsigned short _v59 = 5;

#ifdef OSS_SPARTAN_AWARE
#if ((OSS_SPARTAN_AWARE + 0) >= 3)
extern void DLL_ENTRY _oss_run_SOED_on_INTEL_X86_WINDOWS_AND_WINNT(void);
static void _oss_post_init(struct ossGlobal *world);
#endif /* OSS_SPARTAN_AWARE >= 3 */
#endif /* OSS_SPARTAN_AWARE */

#ifdef OSS_SPARTAN_AWARE
#if ((OSS_SPARTAN_AWARE + 0) >= 12)
static unsigned char _privateFlags[] = {0x08,0x00,0x00};
#endif /* OSS_SPARTAN_AWARE >= 12 */
#endif /* OSS_SPARTAN_AWARE */

void DLL_ENTRY_FDEF _ossinit_kekeo_asn1(struct ossGlobal *world) {
#ifdef OSS_SPARTAN_AWARE
#if ((OSS_SPARTAN_AWARE + 0) >= 3)
    _oss_run_SOED_on_INTEL_X86_WINDOWS_AND_WINNT();
#endif /* OSS_SPARTAN_AWARE >= 3 */
#endif /* OSS_SPARTAN_AWARE */
#ifdef OSS_SPARTAN_AWARE
#if ((OSS_SPARTAN_AWARE + 0) >= 12)
    ossPrivateSetMoreFlags(world, 18, _privateFlags);
#endif /* OSS_SPARTAN_AWARE >= 12 */
#endif /* OSS_SPARTAN_AWARE */
    ossLinkBer(world);
    ossLinkDer(world);
#if !defined(OSS_SPARTAN_AWARE) || ((OSS_SPARTAN_AWARE + 0) < 8)
    ossLinkConstraint(world);
#else  /* OSS_SPARTAN_AWARE < 8 */
    ossLinkConstraintSpartanAware8(world);
#endif /* OSS_SPARTAN_AWARE < 8 */

#ifdef OSS_SPARTAN_AWARE
#if ((OSS_SPARTAN_AWARE + 0) >= 3)
    _oss_post_init(world);
#endif /* OSS_SPARTAN_AWARE >= 3 */
#endif /* OSS_SPARTAN_AWARE */
}

static unsigned short const _v63 = 2;
static unsigned int const _v93 = 32;
static unsigned int const _v100 = 32;
static unsigned int const _v102 = 32;
static unsigned int const _v103 = 32;
static unsigned int const _v104 = 32;
static unsigned int const _v111 = 32;
static unsigned int const _v113 = 32;
static unsigned int const _v116 = 32;
static unsigned int const _v134 = 32;
static unsigned short const _v241 = 3;
static unsigned short const _v243 = 2;
static unsigned short const _v299 = 3;
static unsigned short const _v301 = 2;

static unsigned short const _v327[6] = {
  3, 4, 5, 6, 7, 8
};
static unsigned int const _v328[3] = {0, 1, 2};
static int const _v326[2] = {INT_MIN, INT_MAX};
static unsigned int const _v325[2] = {0, UINT_MAX};
static unsigned short const _v324[2] = {1, 128};
static unsigned short const _v322[2] = {1, 8};
static unsigned short const _v320[2] = {1, 40};
static unsigned short const _v318[2] = {1, 15};
static unsigned int const _v316[2] = {1, UINT_MAX};
static unsigned short const _v315[2] = {1, 180};
static unsigned short const _v313[2] = {1, 6};
static unsigned short const _v311[2] = {1, 30};
static unsigned short const _v305[2] = {1, 16};
static unsigned short const _v300[2] = {2, 2};
static unsigned short const _v298[2] = {3, 3};
static unsigned short const _v297[2] = {1, 32};
static unsigned short const _v295[2] = {1, 3};
static unsigned short const _v293[2] = {1, 5};
static unsigned short const _v287[2] = {1, 256};
static unsigned short const _v285[2] = {0, 256};
static unsigned short const _v283[2] = {1, 4};
static unsigned short const _v271[2] = {1, 64};
static unsigned short const _v270[2] = {1, 24};
static unsigned short const _v247[2] = {0, 16};
static unsigned short const _v162[2] = {1, 32768U};
static unsigned int const _v148[2] = {0, 999999};
static unsigned short const _v138[2] = {30, 30};
static unsigned short const _v137[2] = {5, 5};
static unsigned short const _v133[2] = {22, 22};
static unsigned short const _v129[2] = {21, 21};
static unsigned short const _v127[2] = {20, 20};
static unsigned short const _v121[2] = {15, 15};
static unsigned short const _v115[2] = {14, 14};
static unsigned short const _v109[2] = {11, 13};
static unsigned short const _v107[2] = {10, 12};
static unsigned int const _v94[2] = {32, UINT_MAX};

static const unsigned short _pduarray[] = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
    11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
    21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
    31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
    51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
    61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
    71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
    81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
    91
};

static const struct etype _etypearray[] = {
    {-1, 0, 0, "_ObjectID", 8, 2, 2, 4, 40, 0, 63, 0},
    {-1, 2, 5, "Ticket", 36, 4, 0, 0, 8, 0, 12, 0},
    {-1, 21, 24, "EncTicketPart", 128, 11, 1, 4, 8, 4, 12, 0},
    {-1, 76, 79, "AS-REQ", 136, 4, 1, 1, 8, 15, 12, 0},
    {-1, 97, 79, "TGS-REQ", 136, 4, 1, 1, 8, 15, 12, 0},
    {-1, 100, 102, "KDC-REQ-BODY", 124, 12, 1, 7, 8, 19, 12, 0},
    {-1, 166, 169, "AS-REP", 80, 7, 1, 1, 8, 31, 12, 0},
    {-1, 199, 169, "TGS-REP", 80, 7, 1, 1, 8, 31, 12, 0},
    {-1, 202, 205, "EncASRepPart", 144, 13, 1, 5, 8, 38, 12, 0},
    {-1, 265, 205, "EncTGSRepPart", 144, 13, 1, 5, 8, 38, 12, 0},
    {-1, 268, 271, "AP-REQ", 68, 5, 0, 0, 8, 51, 12, 0},
    {-1, 291, 294, "Authenticator", 72, 9, 1, 4, 8, 56, 12, 0},
    {-1, 338, 341, "AP-REP", 24, 3, 0, 0, 8, 65, 12, 0},
    {-1, 353, 356, "EncAPRepPart", 40, 4, 1, 2, 8, 68, 12, 0},
    {-1, 374, 5, "KRB-SAFE", 80, 4, 0, 0, 8, 72, 12, 0},
    {-1, 377, 380, "KRB-PRIV", 24, 3, 0, 0, 8, 76, 12, 0},
    {-1, 392, 395, "EncKrbPrivPart", 64, 6, 1, 4, 8, 79, 12, 0},
    {-1, 431, 5, "KRB-CRED", 28, 4, 0, 0, 8, 85, 12, 0},
    {-1, 434, 437, "EncKrbCredPart", 60, 6, 1, 5, 8, 89, 12, 0},
    {-1, 481, 484, "KRB-ERROR", 92, 13, 1, 6, 8, 95, 12, 0},
    {-1, 100, 0, "METHOD-DATA", 4, 12, 4, 4, 8, 113, 18, 0},
    {-1, 100, 0, "TYPED-DATA", 4, 16, 4, 4, 72, 267, 18, 0},
    {-1, 100, 550, "PA-ENC-TIMESTAMP", 20, 3, 1, 1, 8, 108, 12, 0},
    {-1, 100, 564, "PA-ENC-TS-ENC", 24, 2, 1, 1, 8, 111, 12, 0},
    {-1, 100, 0, "ETYPE-INFO", 4, 16, 4, 4, 8, 272, 18, 0},
    {-1, 100, 0, "ETYPE-INFO2", 4, 20, 4, 4, 72, 276, 18, 2},
    {-1, 100, 0, "AD-IF-RELEVANT", 4, 12, 4, 4, 8, 109, 18, 0},
    {-1, 100, 572, "AD-KDCIssued", 32, 4, 1, 2, 8, 113, 12, 0},
    {-1, 100, 564, "AD-AND-OR", 8, 2, 0, 0, 8, 117, 12, 0},
    {-1, 100, 0, "AD-MANDATORY-FOR-KDC", 4, 12, 4, 4, 8, 109, 18, 0},
    {-1, 100, 550, "ChangePasswdData", 24, 3, 1, 2, 8, 119, 12, 0},
    {-1, 100, 550, "PA-PK-AS-REQ", 24, 3, 1, 2, 12, 122, 12, 0},
    {-1, 100, 572, "AuthPack", 84, 4, 1, 3, 12, 125, 12, 0},
    {-1, 100, 0, "TD-TRUSTED-CERTIFIERS", 4, 28, 4, 4, 8, 289, 18, 0},
    {-1, 100, 0, "TD-INVALID-CERTIFICATES", 4, 28, 4, 4, 8, 289, 18, 0},
    {-1, 100, 564, "KRB5PrincipalName", 12, 2, 0, 0, 8, 129, 12, 0},
    {-1, 100, 0, "AD-INITIAL-VERIFIED-CAS", 4, 28, 4, 4, 8, 289, 18, 0},
    {-1, 594, 595, "PA-PK-AS-REP", 24, 2, 2, 4, 12, 131, 13, 0},
    {-1, 100, 341, "KDCDHKeyInfo", 36, 3, 1, 1, 12, 133, 12, 0},
    {-1, 100, 564, "ReplyKeyPack", 24, 2, 0, 0, 12, 136, 12, 0},
    {-1, 100, 0, "TD-DH-PARAMETERS", 4, 20, 4, 4, 8, 300, 18, 0},
    {-1, 100, 602, "Attribute", 12, 2, 0, 0, 8, 138, 12, 0},
    {-1, 594, 610, "X520name", 12, 5, 2, 4, 8, 140, 13, 0},
    {-1, 594, 610, "X520CommonName", 392, 5, 2, 4, 8, 145, 13, 0},
    {-1, 594, 610, "X520LocalityName", 776, 5, 2, 4, 8, 150, 13, 0},
    {-1, 594, 610, "X520StateOrProvinceName", 776, 5, 2, 4, 8, 155, 13, 0},
    {-1, 594, 610, "X520OrganizationName", 392, 5, 2, 4, 8, 160, 13, 0},
    {-1, 594, 610, "X520OrganizationalUnitName", 392, 5, 2, 4, 8, 165, 13, 0},
    {-1, 594, 610, "X520Title", 392, 5, 2, 4, 8, 170, 13, 0},
    {0, 621, 19, "X520dnQualifier", 1, 0, 4, 0, 9, 0, 24, 0},
    {3, 621, 19, "X520countryName", 1, 0, 2, 0, 8408, 0, 24, 4},
    {65, 621, 19, "X520SerialNumber", 1, 0, 2, 0, 216, 0, 24, 7},
    {-1, 594, 610, "X520Pseudonym", 776, 5, 2, 4, 8, 175, 13, 0},
    {0, 623, 22, "DomainComponent", 1, 0, 4, 0, 9, 0, 24, 0},
    {129, 623, 22, "EmailAddress", 1, 0, 2, 0, 216, 0, 24, 10},
    {-1, 100, 0, "DistinguishedName", 4, 4, 4, 4, 8, 365, 18, 0},
    {-1, 594, 610, "DirectoryString", 12, 5, 2, 4, 8, 180, 13, 0},
    {-1, 100, 625, "Certificate", 164, 3, 0, 0, 8, 185, 12, 0},
    {-1, 100, 625, "CertificateList", 112, 3, 0, 0, 8, 188, 12, 0},
    {-1, 100, 637, "ORAddress", 276, 3, 1, 2, 8, 191, 12, 0},
    {65, 621, 19, "CommonName", 1, 0, 2, 0, 216, 0, 24, 13},
    {65, 651, 20, "TeletexCommonName", 1, 0, 2, 0, 216, 0, 24, 16},
    {65, 651, 20, "TeletexOrganizationName", 1, 0, 2, 0, 216, 0, 24, 19},
    {-1, 653, 655, "TeletexPersonalName", 69, 4, 1, 3, 8200, 194, 11, 0},
    {4, 100, 0, "TeletexOrganizationalUnitNames", 4, 36, 2, 4, 216, 432, 18, 22},
    {17, 621, 19, "PDSName", 1, 0, 2, 0, 216, 0, 24, 25},
    {-1, 594, 664, "PhysicalDeliveryCountryName", 6, 2, 2, 2, 8, 198, 13, 0},
    {-1, 594, 664, "PostalCode", 20, 2, 2, 2, 8, 200, 13, 0},
    {-1, 653, 669, "PhysicalDeliveryOfficeName", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 653, 669, "PhysicalDeliveryOfficeNumber", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 653, 669, "ExtensionORAddressComponents", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 653, 669, "PhysicalDeliveryPersonalName", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 653, 669, "PhysicalDeliveryOrganizationName", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 653, 669, "ExtensionPhysicalDeliveryAddressComponents", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 653, 674, "UnformattedPostalAddress", 192, 2, 1, 2, 8200, 204, 11, 0},
    {-1, 653, 669, "StreetAddress", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 653, 669, "PostOfficeBoxAddress", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 653, 669, "PosteRestanteAddress", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 653, 669, "UniquePostalName", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 653, 669, "LocalPostalAttributes", 63, 2, 1, 2, 8200, 202, 11, 0},
    {-1, 594, 679, "ExtendedNetworkAddress", 64, 2, 2, 4, 8, 206, 13, 0},
    {-1, 684, 0, "TerminalType", 2, 131072, 2, 0, 200, 1, 55, 28},
    {4, 100, 0, "TeletexDomainDefinedAttributes", 4, 140, 2, 4, 216, 454, 18, 30},
    {-1, 100, 686, "AuthPack_OLD", 40, 1, 0, 0, 8, 208, 12, 0},
    {-1, 100, 564, "KERB-REPLY-KEY-PACKAGE", 16, 2, 0, 0, 12, 209, 12, 0},
    {-1, 100, 5, "PA-FOR-USER-ENC", 28, 4, 0, 0, 8, 211, 12, 0},
    {-1, 100, 564, "PA-S4U-X509-USER", 48, 2, 0, 0, 8, 215, 12, 0},
    {-1, 100, 690, "PA-PAC-OPTIONS", 8, 1, 0, 0, 8, 217, 12, 0},
    {-1, 100, 686, "KERB-PA-PAC-REQUEST", 1, 1, 0, 0, 8, 218, 12, 0},
    {-1, 694, 0, "KERB-LOCAL", 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 564, "KERB-AD-RESTRICTION-ENTRY", 12, 2, 0, 0, 8, 219, 12, 0},
    {-1, 684, 0, "PA-SUPPORTED-ENCTYPES", 4, 262144, 4, 0, 200, 0, 0, 33},
    {-1, 594, 0, "_Any", 8, 0, 4, 4, 40, 0, 10, 0},
    {-1, 684, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 35},
    {-1, 684, 0, "UInt32", 4, 262144, 4, 0, 200, 0, 55, 37},
    {-1, 684, 0, "Microseconds", 4, 262144, 4, 0, 200, 0, 55, 39},
    {-1, 623, 22, NULL, 8, 0, 4, 4, 8, 0, 25, 0},
    {0, 696, 27, "KerberosString", 1, 0, 4, 0, 73, 0, 24, 41},
    {0, 696, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 42},
    {-1, 701, 0, "_seqof1", 4, 4, 4, 4, 40, 97, 18, 0},
    {-1, 100, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 704, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 44},
    {-1, 706, 0, "_octet1", 8, 0, 4, 4, 40, 0, 20, 0},
    {-1, 100, 564, "HostAddress", 12, 2, 0, 0, 8, 223, 12, 0},
    {-1, 100, 0, "HostAddresses", 4, 12, 4, 4, 8, 105, 18, 0},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 46},
    {-1, 706, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 564, NULL, 12, 2, 0, 0, 8, 225, 12, 0},
    {-1, 100, 0, "AuthorizationData", 4, 12, 4, 4, 8, 109, 18, 0},
    {-1, 709, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 48},
    {-1, 712, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 715, "PA-DATA", 12, 2, 0, 0, 8, 227, 12, 0},
    {-1, 723, 0, "KerberosFlags", 8, 0, 4, 4, 200, 0, 3, 50},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 53},
    {-1, 709, 0, "UInt32", 4, 262144, 4, 0, 200, 0, 55, 55},
    {-1, 712, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 550, "EncryptedData", 20, 3, 1, 1, 8, 108, 12, 0},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 57},
    {-1, 706, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 564, "EncryptionKey", 12, 2, 0, 0, 8, 229, 12, 0},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 59},
    {-1, 706, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 564, "Checksum", 12, 2, 0, 0, 8, 231, 12, 0},
    {-1, 698, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 61},
    {0, 725, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 728, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 731, 550, "EncryptedData", 20, 3, 1, 1, 8, 108, 12, 0},
    {-1, 723, 0, "TicketFlags", 8, 0, 4, 4, 200, 0, 3, 63},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 65},
    {-1, 706, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 564, "TransitedEncoding", 12, 2, 0, 0, 8, 233, 12, 0},
    {-1, 734, 0, "TicketFlags", 8, 0, 4, 4, 200, 0, 3, 67},
    {-1, 701, 564, "EncryptionKey", 12, 2, 0, 0, 8, 229, 12, 0},
    {0, 737, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 731, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 740, 564, "TransitedEncoding", 12, 2, 0, 0, 8, 233, 12, 0},
    {-1, 743, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 746, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 749, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 752, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 755, 0, "HostAddresses", 4, 12, 4, 4, 8, 105, 18, 0},
    {-1, 758, 0, "AuthorizationData", 4, 12, 4, 4, 8, 109, 18, 0},
    {-1, 723, 0, "KDCOptions", 8, 0, 4, 4, 200, 0, 3, 69},
    {-1, 734, 0, "KDCOptions", 8, 0, 4, 4, 200, 0, 3, 71},
    {-1, 701, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {0, 737, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 731, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 761, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 743, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 746, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 764, 0, "UInt32", 4, 262144, 4, 0, 200, 0, 55, 73},
    {-1, 767, 0, "_seqof2", 4, 4, 4, 4, 40, 93, 18, 0},
    {-1, 755, 0, "HostAddresses", 4, 12, 4, 4, 8, 105, 18, 0},
    {-1, 758, 550, "EncryptedData", 20, 3, 1, 1, 8, 108, 12, 0},
    {-1, 770, 0, "_seqof3", 4, 36, 4, 4, 40, 1, 18, 0},
    {-1, 709, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 75},
    {-1, 773, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 77},
    {-1, 731, 0, "_seqof4", 4, 12, 4, 4, 40, 113, 18, 0},
    {-1, 740, 102, "KDC-REQ-BODY", 124, 12, 1, 7, 8, 19, 12, 0},
    {-1, 100, 79, "KDC-REQ", 136, 4, 1, 1, 8, 15, 12, 0},
    {-1, 698, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 80},
    {-1, 709, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 82},
    {-1, 728, 0, "", 4, 12, 4, 4, 40, 113, 18, 0},
    {0, 776, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 740, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 779, 5, "Ticket", 36, 4, 0, 0, 8, 0, 12, 0},
    {-1, 783, 550, "EncryptedData", 20, 3, 1, 1, 8, 108, 12, 0},
    {-1, 100, 169, "KDC-REP", 80, 7, 1, 1, 8, 31, 12, 0},
    {-1, 786, 564, "EncryptionKey", 12, 2, 0, 0, 8, 229, 12, 0},
    {-1, 701, 0, "LastReq", 4, 24, 4, 4, 8, 186, 18, 0},
    {-1, 773, 0, "UInt32", 4, 262144, 4, 0, 200, 0, 55, 85},
    {-1, 789, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 792, 0, "TicketFlags", 8, 0, 4, 4, 200, 0, 3, 87},
    {-1, 743, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 746, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 749, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 752, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {0, 795, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 758, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 770, 0, "HostAddresses", 4, 12, 4, 4, 8, 105, 18, 0},
    {-1, 798, 0, "", 4, 12, 4, 4, 40, 113, 18, 0},
    {-1, 100, 205, "EncKDCRepPart", 144, 13, 1, 5, 8, 38, 12, 0},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 89},
    {-1, 801, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 100, 564, NULL, 24, 2, 0, 0, 8, 235, 12, 0},
    {-1, 100, 0, "LastReq", 4, 24, 4, 4, 8, 186, 18, 0},
    {-1, 723, 0, "APOptions", 8, 0, 4, 4, 200, 0, 3, 91},
    {-1, 698, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 93},
    {-1, 709, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 95},
    {-1, 804, 0, "APOptions", 8, 0, 4, 4, 200, 0, 3, 97},
    {-1, 807, 5, "Ticket", 36, 4, 0, 0, 8, 0, 12, 0},
    {-1, 740, 550, "EncryptedData", 20, 3, 1, 1, 8, 108, 12, 0},
    {-1, 698, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 99},
    {0, 725, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 728, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 731, 564, "Checksum", 12, 2, 0, 0, 8, 231, 12, 0},
    {-1, 811, 0, "Microseconds", 4, 262144, 4, 0, 200, 0, 55, 101},
    {-1, 743, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 783, 564, "EncryptionKey", 12, 2, 0, 0, 8, 229, 12, 0},
    {-1, 764, 0, "UInt32", 4, 262144, 4, 0, 200, 0, 55, 103},
    {-1, 767, 0, "AuthorizationData", 4, 12, 4, 4, 8, 109, 18, 0},
    {-1, 698, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 105},
    {-1, 709, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 107},
    {-1, 728, 550, "EncryptedData", 20, 3, 1, 1, 8, 108, 12, 0},
    {-1, 814, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 709, 0, "Microseconds", 4, 262144, 4, 0, 200, 0, 55, 109},
    {-1, 728, 564, "EncryptionKey", 12, 2, 0, 0, 8, 229, 12, 0},
    {-1, 817, 0, "UInt32", 4, 262144, 4, 0, 200, 0, 55, 111},
    {-1, 820, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 801, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 773, 0, "Microseconds", 4, 262144, 4, 0, 200, 0, 55, 113},
    {-1, 817, 0, "UInt32", 4, 262144, 4, 0, 200, 0, 55, 115},
    {-1, 740, 564, "HostAddress", 12, 2, 0, 0, 8, 223, 12, 0},
    {-1, 823, 564, "HostAddress", 12, 2, 0, 0, 8, 223, 12, 0},
    {-1, 100, 395, "KRB-SAFE-BODY", 64, 6, 1, 4, 8, 237, 12, 0},
    {-1, 698, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 117},
    {-1, 709, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 119},
    {-1, 728, 395, "KRB-SAFE-BODY", 64, 6, 1, 4, 8, 237, 12, 0},
    {-1, 731, 564, "Checksum", 12, 2, 0, 0, 8, 231, 12, 0},
    {-1, 698, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 121},
    {-1, 709, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 123},
    {-1, 731, 550, "EncryptedData", 20, 3, 1, 1, 8, 108, 12, 0},
    {-1, 820, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 801, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 773, 0, "Microseconds", 4, 262144, 4, 0, 200, 0, 55, 125},
    {-1, 817, 0, "UInt32", 4, 262144, 4, 0, 200, 0, 55, 127},
    {-1, 740, 564, "HostAddress", 12, 2, 0, 0, 8, 223, 12, 0},
    {-1, 823, 564, "HostAddress", 12, 2, 0, 0, 8, 223, 12, 0},
    {-1, 698, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 129},
    {-1, 709, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 131},
    {-1, 728, 0, "", 4, 36, 4, 4, 40, 1, 18, 0},
    {-1, 731, 550, "EncryptedData", 20, 3, 1, 1, 8, 108, 12, 0},
    {-1, 786, 564, "EncryptionKey", 12, 2, 0, 0, 8, 229, 12, 0},
    {0, 725, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 728, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 826, 0, "TicketFlags", 8, 0, 4, 4, 200, 0, 3, 133},
    {-1, 761, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 743, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 746, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 749, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {0, 829, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 755, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 758, 0, "HostAddresses", 4, 12, 4, 4, 8, 105, 18, 0},
    {-1, 100, 832, "KrbCredInfo", 124, 11, 1, 10, 8, 243, 12, 0},
    {-1, 786, 0, "_seqof5", 4, 124, 4, 4, 40, 245, 18, 0},
    {-1, 709, 0, "UInt32", 4, 262144, 4, 0, 200, 0, 55, 135},
    {-1, 966, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 817, 0, "Microseconds", 4, 262144, 4, 0, 200, 0, 55, 137},
    {-1, 740, 564, "HostAddress", 12, 2, 0, 0, 8, 223, 12, 0},
    {-1, 823, 564, "HostAddress", 12, 2, 0, 0, 8, 223, 12, 0},
    {-1, 698, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 139},
    {-1, 709, 0, NULL, 2, 65536, 2, 0, 200, 0, 55, 141},
    {-1, 966, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 817, 0, "Microseconds", 4, 262144, 4, 0, 200, 0, 55, 143},
    {-1, 761, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 969, 0, "Microseconds", 4, 262144, 4, 0, 200, 0, 55, 145},
    {-1, 972, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 147},
    {0, 975, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 767, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {0, 795, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 758, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {0, 978, 27, "KerberosString", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 981, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 149},
    {-1, 706, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 564, NULL, 16, 2, 1, 1, 8, 254, 12, 0},
    {-1, 814, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 709, 0, "Microseconds", 4, 262144, 4, 0, 200, 0, 55, 151},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 153},
    {-1, 706, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 564, "ETYPE-INFO-ENTRY", 16, 2, 1, 1, 8, 256, 12, 0},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 155},
    {0, 725, 27, "KerberosString", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 712, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 550, "ETYPE-INFO2-ENTRY", 20, 3, 1, 2, 8, 258, 12, 0},
    {-1, 786, 564, "Checksum", 12, 2, 0, 0, 8, 231, 12, 0},
    {0, 725, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 728, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 731, 0, "AuthorizationData", 4, 12, 4, 4, 8, 109, 18, 0},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 157},
    {-1, 701, 0, "AuthorizationData", 4, 12, 4, 4, 8, 109, 18, 0},
    {-1, 820, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 701, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {0, 737, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 984, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 986, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 988, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 990, "ExternalPrincipalIdentifier", 28, 3, 1, 3, 12, 261, 12, 0},
    {-1, 984, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 701, 0, "_seqof6", 4, 28, 4, 4, 40, 289, 18, 0},
    {-1, 988, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 694, 0, "DHNonce", 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 698, 0, NULL, 4, 262144, 4, 0, 200, 0, 55, 159},
    {-1, 801, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 773, 0, NULL, 4, 262144, 4, 0, 200, 0, 55, 161},
    {-1, 1008, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 5, "PKAuthenticator", 40, 4, 1, 1, 12, 264, 12, 0},
    {-1, 594, 0, "_Any", 8, 0, 4, 4, 40, 0, 10, 0},
    {-1, 100, 1011, "AlgorithmIdentifier", 20, 2, 1, 1, 8, 268, 12, 0},
    {-1, 723, 0, "_bit1", 8, 0, 4, 4, 40, 0, 3, 0},
    {-1, 100, 1017, "SubjectPublicKeyInfo", 28, 2, 0, 0, 8, 270, 12, 0},
    {-1, 786, 5, "PKAuthenticator", 40, 4, 1, 1, 12, 264, 12, 0},
    {-1, 701, 1017, "SubjectPublicKeyInfo", 28, 2, 0, 0, 8, 270, 12, 0},
    {-1, 728, 0, "_seqof7", 4, 20, 4, 4, 40, 300, 18, 0},
    {-1, 1008, 0, "DHNonce", 8, 0, 4, 4, 8, 0, 20, 0},
    {0, 1025, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 701, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {-1, 984, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 706, 0, "DHNonce", 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 100, 564, "DHRepInfo", 20, 2, 1, 1, 12, 272, 12, 0},
    {-1, 786, 564, "DHRepInfo", 20, 2, 1, 1, 12, 272, 12, 0},
    {-1, 986, 0, "", 8, 0, 4, 4, 40, 0, 20, 0},
    {-1, 734, 0, NULL, 8, 0, 4, 4, 8, 0, 3, 0},
    {-1, 709, 0, NULL, 4, 262144, 4, 0, 200, 0, 55, 163},
    {-1, 966, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 786, 564, "EncryptionKey", 12, 2, 0, 0, 8, 229, 12, 0},
    {-1, 701, 564, "Checksum", 12, 2, 0, 0, 8, 231, 12, 0},
    {-1, 0, 0, "AttributeType", 8, 2, 2, 4, 8, 0, 63, 0},
    {-1, 594, 0, "AttributeValue", 8, 0, 4, 4, 8, 0, 10, 0},
    {-1, 653, 0, "_setof1", 4, 8, 4, 4, 40, 320, 15, 0},
    {-1, 100, 1011, "AttributeTypeAndValue", 16, 2, 0, 0, 8, 274, 12, 0},
    {32768, 651, 20, "_char1", 8, 0, 2, 4, 248, 0, 25, 165},
    {32768, 621, 19, "", 8, 0, 2, 4, 248, 0, 25, 168},
    {32768, 1028, 28, "_char2", 8, 0, 2, 4, 248, 0, 54, 171},
    {196608, 1030, 12, "_char3", 8, 0, 2, 4, 248, 0, 25, 174},
    {32768, 1032, 30, "_char4", 8, 0, 2, 4, 248, 0, 53, 177},
    {65, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 180},
    {65, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 183},
    {64, 1028, 28, "", 8, 0, 2, 4, 248, 0, 54, 186},
    {385, 1030, 12, NULL, 1, 0, 2, 0, 216, 0, 24, 189},
    {64, 1032, 30, "", 8, 0, 2, 4, 248, 0, 53, 192},
    {129, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 195},
    {129, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 198},
    {128, 1028, 28, "", 8, 0, 2, 4, 248, 0, 54, 201},
    {769, 1030, 12, NULL, 1, 0, 2, 0, 216, 0, 24, 204},
    {128, 1032, 30, "", 8, 0, 2, 4, 248, 0, 53, 207},
    {129, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 210},
    {129, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 213},
    {128, 1028, 28, "", 8, 0, 2, 4, 248, 0, 54, 216},
    {769, 1030, 12, NULL, 1, 0, 2, 0, 216, 0, 24, 219},
    {128, 1032, 30, "", 8, 0, 2, 4, 248, 0, 53, 222},
    {65, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 225},
    {65, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 228},
    {64, 1028, 28, "", 8, 0, 2, 4, 248, 0, 54, 231},
    {385, 1030, 12, NULL, 1, 0, 2, 0, 216, 0, 24, 234},
    {64, 1032, 30, "", 8, 0, 2, 4, 248, 0, 53, 237},
    {65, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 240},
    {65, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 243},
    {64, 1028, 28, "", 8, 0, 2, 4, 248, 0, 54, 246},
    {385, 1030, 12, NULL, 1, 0, 2, 0, 216, 0, 24, 249},
    {64, 1032, 30, "", 8, 0, 2, 4, 248, 0, 53, 252},
    {65, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 255},
    {65, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 258},
    {64, 1028, 28, "", 8, 0, 2, 4, 248, 0, 54, 261},
    {385, 1030, 12, NULL, 1, 0, 2, 0, 216, 0, 24, 264},
    {64, 1032, 30, "", 8, 0, 2, 4, 248, 0, 53, 267},
    {129, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 270},
    {129, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 273},
    {128, 1028, 28, "", 8, 0, 2, 4, 248, 0, 54, 276},
    {769, 1030, 12, NULL, 1, 0, 2, 0, 216, 0, 24, 279},
    {128, 1032, 30, "", 8, 0, 2, 4, 248, 0, 53, 282},
    {-1, 594, 1034, "Name", 8, 1, 2, 4, 8, 276, 13, 0},
    {-1, 100, 0, "RDNSequence", 4, 4, 4, 4, 8, 365, 18, 0},
    {-1, 653, 0, "RelativeDistinguishedName", 4, 16, 4, 4, 72, 322, 15, 285},
    {0, 651, 20, NULL, 1, 0, 4, 0, 73, 0, 24, 287},
    {0, 621, 19, NULL, 1, 0, 4, 0, 73, 0, 24, 289},
    {-1, 1028, 28, "_char5", 8, 0, 4, 4, 104, 0, 54, 291},
    {0, 1030, 12, NULL, 1, 0, 4, 0, 73, 0, 24, 293},
    {-1, 1032, 30, "_char6", 8, 0, 4, 4, 104, 0, 53, 295},
    {-1, 684, 0, "Version", 4, 0, 4, 0, 8, 9, 0, 0},
    {-1, 684, 0, "CertificateSerialNumber", 4, 0, 4, 0, 8, 0, 0, 0},
    {-1, 1037, 0, NULL, 18, 0, 0, 0, 8, 0, 29, 0},
    {-1, 704, 0, NULL, 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 594, 1039, "Time", 20, 2, 2, 2, 8, 277, 13, 0},
    {-1, 100, 1044, "Validity", 40, 2, 0, 0, 8, 279, 12, 0},
    {-1, 723, 0, "UniqueIdentifier", 8, 0, 4, 4, 8, 0, 3, 0},
    {-1, 698, 0, "Version", 4, 0, 4, 0, 8, 9, 0, 0},
    {-1, 986, 0, "UniqueIdentifier", 8, 0, 4, 4, 8, 0, 3, 0},
    {-1, 988, 0, "UniqueIdentifier", 8, 0, 4, 4, 8, 0, 3, 0},
    {-1, 731, 0, "Extensions", 4, 24, 4, 4, 72, 385, 18, 297},
    {-1, 100, 1056, "TBSCertificate", 136, 10, 1, 4, 8, 281, 12, 0},
    {-1, 1104, 0, NULL, 1, 0, 0, 0, 8, 0, 8, 0},
    {-1, 694, 0, "", 8, 0, 4, 4, 40, 0, 20, 0},
    {-1, 100, 1106, "Extension", 24, 3, 1, 1, 8, 291, 12, 0},
    {-1, 100, 0, "Extensions", 4, 24, 4, 4, 72, 385, 18, 297},
    {-1, 100, 1120, NULL, 32, 3, 1, 1, 8, 294, 12, 0},
    {-1, 100, 0, "_seqof8", 4, 32, 4, 4, 40, 387, 18, 0},
    {-1, 786, 0, "Extensions", 4, 24, 4, 4, 72, 385, 18, 297},
    {-1, 100, 1134, "TBSCertList", 84, 7, 1, 4, 8, 297, 12, 0},
    {4, 1174, 18, NULL, 1, 0, 2, 0, 8408, 0, 24, 299},
    {3, 621, 19, NULL, 1, 0, 2, 0, 8408, 0, 24, 302},
    {-1, 1176, 664, "CountryName", 6, 2, 2, 2, 8, 304, 13, 0},
    {17, 1174, 18, NULL, 1, 0, 2, 0, 216, 0, 24, 305},
    {17, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 308},
    {-1, 1178, 664, "AdministrationDomainName", 20, 2, 2, 2, 8, 306, 13, 0},
    {17, 1174, 18, "X121Address", 1, 0, 2, 0, 216, 0, 24, 311},
    {17, 1174, 18, "NetworkAddress", 1, 0, 2, 0, 216, 0, 24, 314},
    {25, 621, 19, "TerminalIdentifier", 1, 0, 2, 0, 216, 0, 24, 316},
    {17, 1174, 18, NULL, 1, 0, 2, 0, 216, 0, 24, 319},
    {17, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 322},
    {-1, 594, 664, "PrivateDomainName", 20, 2, 2, 2, 8, 308, 13, 0},
    {65, 621, 19, "OrganizationName", 1, 0, 2, 0, 216, 0, 24, 325},
    {33, 1174, 18, "NumericUserIdentifier", 1, 0, 2, 0, 216, 0, 24, 328},
    {41, 984, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 331},
    {17, 986, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 334},
    {6, 988, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 337},
    {4, 1180, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 340},
    {-1, 653, 655, "PersonalName", 69, 4, 1, 3, 8200, 310, 11, 0},
    {17, 984, 18, "NetworkAddress", 1, 0, 2, 0, 216, 0, 24, 343},
    {25, 986, 19, "TerminalIdentifier", 1, 0, 2, 0, 216, 0, 24, 345},
    {-1, 988, 664, "PrivateDomainName", 20, 2, 2, 2, 8, 308, 13, 0},
    {65, 1180, 19, "OrganizationName", 1, 0, 2, 0, 216, 0, 24, 347},
    {33, 1182, 18, "NumericUserIdentifier", 1, 0, 2, 0, 216, 0, 24, 349},
    {-1, 1184, 655, "PersonalName", 69, 4, 1, 3, 8200, 310, 11, 0},
    {4, 1186, 0, "OrganizationalUnitNames", 4, 36, 2, 4, 216, 418, 18, 351},
    {-1, 100, 1188, "BuiltInStandardAttributes", 264, 9, 2, 9, 8, 314, 12, 0},
    {33, 621, 19, "OrganizationalUnitName", 1, 0, 2, 0, 216, 0, 24, 354},
    {4, 100, 0, "OrganizationalUnitNames", 4, 36, 2, 4, 216, 418, 18, 357},
    {9, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 359},
    {129, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 362},
    {-1, 100, 1296, "BuiltInDomainDefinedAttribute", 138, 2, 0, 0, 8, 323, 12, 0},
    {4, 100, 0, "BuiltInDomainDefinedAttributes", 4, 140, 2, 4, 216, 422, 18, 365},
    {-1, 984, 0, NULL, 2, 131072, 2, 0, 200, 0, 55, 368},
    {-1, 986, 0, "_Any", 8, 0, 4, 4, 40, 0, 10, 0},
    {-1, 100, 564, "ExtensionAttribute", 12, 2, 0, 0, 8, 325, 12, 0},
    {256, 653, 0, "ExtensionAttributes", 4, 12, 2, 4, 216, 426, 15, 370},
    {41, 984, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 373},
    {17, 986, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 376},
    {6, 988, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 379},
    {4, 1180, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 382},
    {33, 651, 20, "TeletexOrganizationalUnitName", 1, 0, 2, 0, 216, 0, 24, 385},
    {4, 1174, 18, NULL, 1, 0, 2, 0, 8408, 0, 24, 388},
    {3, 621, 19, NULL, 1, 0, 2, 0, 8408, 0, 24, 391},
    {17, 1174, 18, NULL, 1, 0, 2, 0, 216, 0, 24, 394},
    {17, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 397},
    {31, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 400},
    {31, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 403},
    {-1, 653, 669, "PDSParameter", 63, 2, 1, 2, 8200, 202, 11, 0},
    {31, 621, 19, NULL, 1, 0, 2, 0, 216, 0, 24, 406},
    {6, 100, 0, "_seqof9", 4, 32, 2, 4, 248, 440, 18, 409},
    {181, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 412},
    {-1, 820, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 706, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 712, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 1304, 0, "_setof2", 4, 8, 4, 4, 104, 384, 15, 415},
    {-1, 100, 1307, "PresentationAddress", 32, 4, 1, 3, 8, 327, 12, 0},
    {16, 984, 18, NULL, 1, 0, 2, 0, 216, 0, 24, 417},
    {41, 986, 18, NULL, 1, 0, 2, 0, 216, 0, 24, 420},
    {-1, 100, 564, "_seq1", 58, 2, 1, 1, 40, 331, 12, 0},
    {-1, 984, 1307, "PresentationAddress", 32, 4, 1, 3, 8, 327, 12, 0},
    {9, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 423},
    {129, 651, 20, NULL, 1, 0, 2, 0, 216, 0, 24, 426},
    {-1, 100, 1335, "TeletexDomainDefinedAttribute", 138, 2, 0, 0, 8, 333, 12, 0},
    {-1, 786, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {0, 725, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 773, 0, NULL, 4, 0, 4, 0, 8, 0, 0, 0},
    {-1, 789, 0, "KerberosTime", 18, 0, 0, 0, 8, 0, 30, 0},
    {-1, 811, 0, NULL, 4, 0, 4, 0, 8, 0, 0, 0},
    {-1, 100, 271, "PKAuthenticator_OLD", 40, 5, 0, 0, 8, 335, 12, 0},
    {-1, 786, 271, "PKAuthenticator_OLD", 40, 5, 0, 0, 8, 335, 12, 0},
    {-1, 786, 564, "EncryptionKey", 12, 2, 0, 0, 8, 229, 12, 0},
    {-1, 709, 0, NULL, 4, 0, 4, 0, 8, 0, 0, 0},
    {-1, 786, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {0, 725, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 728, 564, "Checksum", 12, 2, 0, 0, 8, 231, 12, 0},
    {0, 776, 27, "KerberosString", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 698, 0, "UInt32", 4, 262144, 4, 0, 200, 0, 55, 429},
    {-1, 701, 564, "PrincipalName", 8, 2, 0, 0, 8, 221, 12, 0},
    {0, 737, 27, "Realm", 1, 0, 4, 0, 73, 0, 24, 41},
    {-1, 1008, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0},
    {-1, 792, 0, NULL, 8, 0, 4, 4, 8, 0, 3, 0},
    {-1, 100, 1343, "S4UUserID", 36, 5, 1, 3, 12, 340, 12, 0},
    {-1, 786, 1343, "S4UUserID", 36, 5, 1, 3, 12, 340, 12, 0},
    {-1, 701, 564, "Checksum", 12, 2, 0, 0, 8, 231, 12, 0},
    {-1, 1367, 0, NULL, 1, 0, 0, 0, 8, 0, 8, 0},
    {-1, 698, 0, "Int32", 4, 262144, 4, 0, 200, 0, 0, 431},
    {-1, 706, 0, NULL, 8, 0, 4, 4, 8, 0, 20, 0}
};

static const struct ConstraintEntry _econstraintarray[] = {
    {0, 6, (char *)NULL + 1},
    {0, 3, (void *)_v316},
    {0, 6, (char *)NULL + 3},
    {0, 3, (void *)_v316},
    {5, 14, (void *)_v300},
    {0, 6, (char *)NULL + 6},
    {0, 1, (void *)&_v63},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 9},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 12},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 15},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 18},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 21},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v283},
    {0, 6, (char *)NULL + 24},
    {0, 3, (void *)_v283},
    {5, 14, (void *)_v305},
    {0, 6, (char *)NULL + 27},
    {0, 3, (void *)_v305},
    {5, 14, (void *)_v285},
    {0, 3, (void *)_v285},
    {5, 14, (void *)_v283},
    {0, 6, (char *)NULL + 32},
    {0, 3, (void *)_v283},
    {5, 14, (void *)_v326},
    {0, 3, (void *)_v326},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v325},
    {0, 3, (void *)_v325},
    {5, 14, (void *)_v148},
    {0, 3, (void *)_v148},
    {0, 2, (char *)NULL + 96},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 15, (void *)&_v93},
    {0, 6, (char *)NULL + 52},
    {0, 3, (void *)_v94},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v325},
    {0, 11, (char *)NULL + 38},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v137},
    {0, 1, (void *)&_v59},
    {5, 15, (void *)&_v100},
    {0, 11, (char *)NULL + 51},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 15, (void *)&_v102},
    {0, 11, (char *)NULL + 51},
    {5, 15, (void *)&_v103},
    {0, 11, (char *)NULL + 51},
    {5, 15, (void *)&_v104},
    {0, 11, (char *)NULL + 51},
    {5, 14, (void *)_v325},
    {0, 11, (char *)NULL + 38},
    {5, 14, (void *)_v137},
    {0, 1, (void *)&_v58},
    {5, 14, (void *)_v107},
    {2, 1, (void *)&_v56},
    {0, 1, (void *)&_v57},
    {5, 14, (void *)_v137},
    {0, 1, (void *)&_v55},
    {5, 14, (void *)_v109},
    {2, 1, (void *)&_v53},
    {0, 1, (void *)&_v54},
    {5, 14, (void *)_v325},
    {0, 11, (char *)NULL + 38},
    {5, 15, (void *)&_v111},
    {0, 11, (char *)NULL + 51},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 15, (void *)&_v113},
    {0, 11, (char *)NULL + 51},
    {5, 14, (void *)_v137},
    {0, 1, (void *)&_v52},
    {5, 14, (void *)_v115},
    {0, 1, (void *)&_v51},
    {5, 15, (void *)&_v116},
    {0, 11, (char *)NULL + 51},
    {5, 14, (void *)_v137},
    {0, 1, (void *)&_v50},
    {5, 14, (void *)_v148},
    {0, 11, (char *)NULL + 40},
    {5, 14, (void *)_v325},
    {0, 11, (char *)NULL + 38},
    {5, 14, (void *)_v137},
    {0, 1, (void *)&_v49},
    {5, 14, (void *)_v121},
    {0, 1, (void *)&_v48},
    {5, 14, (void *)_v148},
    {0, 11, (char *)NULL + 40},
    {5, 14, (void *)_v325},
    {0, 11, (char *)NULL + 38},
    {5, 14, (void *)_v148},
    {0, 11, (char *)NULL + 40},
    {5, 14, (void *)_v325},
    {0, 11, (char *)NULL + 38},
    {5, 14, (void *)_v137},
    {0, 1, (void *)&_v47},
    {5, 14, (void *)_v127},
    {0, 1, (void *)&_v46},
    {5, 14, (void *)_v137},
    {0, 1, (void *)&_v45},
    {5, 14, (void *)_v129},
    {0, 1, (void *)&_v44},
    {5, 14, (void *)_v148},
    {0, 11, (char *)NULL + 40},
    {5, 14, (void *)_v325},
    {0, 11, (char *)NULL + 38},
    {5, 14, (void *)_v137},
    {0, 1, (void *)&_v43},
    {5, 14, (void *)_v133},
    {0, 1, (void *)&_v42},
    {5, 15, (void *)&_v134},
    {0, 11, (char *)NULL + 51},
    {5, 14, (void *)_v325},
    {0, 11, (char *)NULL + 38},
    {5, 14, (void *)_v148},
    {0, 11, (char *)NULL + 40},
    {5, 14, (void *)_v137},
    {0, 1, (void *)&_v41},
    {5, 14, (void *)_v138},
    {0, 1, (void *)&_v40},
    {5, 14, (void *)_v148},
    {0, 11, (char *)NULL + 40},
    {5, 14, (void *)_v148},
    {0, 11, (char *)NULL + 40},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v148},
    {0, 11, (char *)NULL + 40},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34},
    {5, 14, (void *)_v148},
    {0, 3, (void *)_v148},
    {5, 14, (void *)_v325},
    {0, 3, (void *)_v325},
    {5, 14, (void *)_v325},
    {0, 3, (void *)_v325},
    {5, 14, (void *)_v162},
    {0, 6, (char *)NULL + 167},
    {0, 3, (void *)_v162},
    {5, 14, (void *)_v162},
    {0, 6, (char *)NULL + 170},
    {0, 3, (void *)_v162},
    {5, 14, (void *)_v162},
    {0, 6, (char *)NULL + 173},
    {0, 3, (void *)_v162},
    {5, 14, (void *)_v162},
    {0, 6, (char *)NULL + 176},
    {0, 3, (void *)_v162},
    {5, 14, (void *)_v162},
    {0, 6, (char *)NULL + 179},
    {0, 3, (void *)_v162},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 182},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 185},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 188},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 191},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 194},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 197},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 200},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 203},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 206},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 209},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 212},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 215},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 218},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 221},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 224},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 227},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 230},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 233},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 236},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 239},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 242},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 245},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 248},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 251},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 254},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 257},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 260},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 263},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 266},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 269},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 272},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 275},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 278},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 281},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 284},
    {0, 3, (void *)_v324},
    {0, 6, (char *)NULL + 286},
    {0, 3, (void *)_v316},
    {0, 6, (char *)NULL + 288},
    {0, 3, (void *)_v316},
    {0, 6, (char *)NULL + 290},
    {0, 3, (void *)_v316},
    {0, 6, (char *)NULL + 292},
    {0, 3, (void *)_v316},
    {0, 6, (char *)NULL + 294},
    {0, 3, (void *)_v316},
    {0, 6, (char *)NULL + 296},
    {0, 3, (void *)_v316},
    {0, 6, (char *)NULL + 298},
    {0, 3, (void *)_v316},
    {5, 14, (void *)_v298},
    {0, 6, (char *)NULL + 301},
    {0, 1, (void *)&_v241},
    {5, 14, (void *)_v300},
    {0, 6, (char *)NULL + 304},
    {0, 1, (void *)&_v243},
    {5, 14, (void *)_v247},
    {0, 6, (char *)NULL + 307},
    {0, 3, (void *)_v247},
    {5, 14, (void *)_v247},
    {0, 6, (char *)NULL + 310},
    {0, 3, (void *)_v247},
    {5, 14, (void *)_v305},
    {0, 6, (char *)NULL + 313},
    {0, 3, (void *)_v305},
    {5, 14, (void *)_v305},
    {0, 11, (char *)NULL + 312},
    {5, 14, (void *)_v270},
    {0, 6, (char *)NULL + 318},
    {0, 3, (void *)_v270},
    {5, 14, (void *)_v305},
    {0, 6, (char *)NULL + 321},
    {0, 3, (void *)_v305},
    {5, 14, (void *)_v305},
    {0, 6, (char *)NULL + 324},
    {0, 3, (void *)_v305},
    {5, 14, (void *)_v271},
    {0, 6, (char *)NULL + 327},
    {0, 3, (void *)_v271},
    {5, 14, (void *)_v297},
    {0, 6, (char *)NULL + 330},
    {0, 3, (void *)_v297},
    {5, 14, (void *)_v320},
    {0, 6, (char *)NULL + 333},
    {0, 3, (void *)_v320},
    {5, 14, (void *)_v305},
    {0, 6, (char *)NULL + 336},
    {0, 3, (void *)_v305},
    {5, 14, (void *)_v293},
    {0, 6, (char *)NULL + 339},
    {0, 3, (void *)_v293},
    {5, 14, (void *)_v295},
    {0, 6, (char *)NULL + 342},
    {0, 3, (void *)_v295},
    {5, 14, (void *)_v305},
    {0, 11, (char *)NULL + 312},
    {5, 14, (void *)_v270},
    {0, 11, (char *)NULL + 317},
    {5, 14, (void *)_v271},
    {0, 11, (char *)NULL + 326},
    {5, 14, (void *)_v297},
    {0, 11, (char *)NULL + 329},
    {5, 14, (void *)_v283},
    {0, 6, (char *)NULL + 353},
    {0, 3, (void *)_v283},
    {5, 14, (void *)_v297},
    {0, 6, (char *)NULL + 356},
    {0, 3, (void *)_v297},
    {5, 14, (void *)_v283},
    {0, 11, (char *)NULL + 352},
    {5, 14, (void *)_v322},
    {0, 6, (char *)NULL + 361},
    {0, 3, (void *)_v322},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 364},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v283},
    {0, 6, (char *)NULL + 367},
    {0, 3, (void *)_v283},
    {5, 14, (void *)_v285},
    {0, 3, (void *)_v285},
    {5, 14, (void *)_v287},
    {0, 6, (char *)NULL + 372},
    {0, 3, (void *)_v287},
    {5, 14, (void *)_v320},
    {0, 6, (char *)NULL + 375},
    {0, 3, (void *)_v320},
    {5, 14, (void *)_v305},
    {0, 6, (char *)NULL + 378},
    {0, 3, (void *)_v305},
    {5, 14, (void *)_v293},
    {0, 6, (char *)NULL + 381},
    {0, 3, (void *)_v293},
    {5, 14, (void *)_v295},
    {0, 6, (char *)NULL + 384},
    {0, 3, (void *)_v295},
    {5, 14, (void *)_v297},
    {0, 6, (char *)NULL + 387},
    {0, 3, (void *)_v297},
    {5, 14, (void *)_v298},
    {0, 6, (char *)NULL + 390},
    {0, 1, (void *)&_v299},
    {5, 14, (void *)_v300},
    {0, 6, (char *)NULL + 393},
    {0, 1, (void *)&_v301},
    {5, 14, (void *)_v305},
    {0, 6, (char *)NULL + 396},
    {0, 3, (void *)_v305},
    {5, 14, (void *)_v305},
    {0, 6, (char *)NULL + 399},
    {0, 3, (void *)_v305},
    {5, 14, (void *)_v311},
    {0, 6, (char *)NULL + 402},
    {0, 3, (void *)_v311},
    {5, 14, (void *)_v311},
    {0, 6, (char *)NULL + 405},
    {0, 3, (void *)_v311},
    {5, 14, (void *)_v311},
    {0, 6, (char *)NULL + 408},
    {0, 3, (void *)_v311},
    {5, 14, (void *)_v313},
    {0, 6, (char *)NULL + 411},
    {0, 3, (void *)_v313},
    {5, 14, (void *)_v315},
    {0, 6, (char *)NULL + 414},
    {0, 3, (void *)_v315},
    {0, 6, (char *)NULL + 416},
    {0, 3, (void *)_v316},
    {5, 14, (void *)_v318},
    {0, 6, (char *)NULL + 419},
    {0, 3, (void *)_v318},
    {5, 14, (void *)_v320},
    {0, 6, (char *)NULL + 422},
    {0, 3, (void *)_v320},
    {5, 14, (void *)_v322},
    {0, 6, (char *)NULL + 425},
    {0, 3, (void *)_v322},
    {5, 14, (void *)_v324},
    {0, 6, (char *)NULL + 428},
    {0, 3, (void *)_v324},
    {5, 14, (void *)_v325},
    {0, 11, (char *)NULL + 38},
    {5, 14, (void *)_v326},
    {0, 11, (char *)NULL + 34}
};

static const struct efield _efieldarray[] = {
    {0, 125, -1, 14, 2},
    {4, 126, -1, 15, 2},
    {8, 127, -1, 16, 2},
    {16, 128, -1, 17, 2},
    {4, 133, -1, 18, 2},
    {12, 134, -1, 19, 2},
    {24, 135, -1, 20, 2},
    {28, 136, -1, 21, 2},
    {36, 137, -1, 22, 2},
    {48, 138, -1, 23, 2},
    {66, 139, 0, 24, 3},
    {84, 140, -1, 25, 2},
    {102, 141, 1, 26, 3},
    {120, 142, 2, 27, 3},
    {124, 143, 3, 28, 3},
    {2, 157, -1, 29, 2},
    {4, 158, -1, 30, 2},
    {8, 159, 0, 31, 3},
    {12, 160, -1, 32, 2},
    {4, 145, -1, 33, 2},
    {12, 146, 0, 21, 3},
    {20, 147, -1, 15, 2},
    {24, 148, 1, 16, 3},
    {32, 149, 2, 34, 3},
    {50, 150, -1, 35, 2},
    {68, 151, 3, 36, 3},
    {88, 152, -1, 37, 2},
    {92, 153, -1, 38, 2},
    {96, 154, 4, 39, 3},
    {100, 155, 5, 40, 3},
    {120, 156, 6, 41, 3},
    {2, 162, -1, 29, 2},
    {4, 163, -1, 30, 2},
    {8, 164, 0, 31, 3},
    {12, 165, -1, 20, 2},
    {16, 166, -1, 21, 2},
    {24, 167, -1, 42, 2},
    {60, 168, -1, 17, 2},
    {4, 170, -1, 19, 2},
    {16, 171, -1, 43, 2},
    {20, 172, -1, 37, 2},
    {24, 173, 0, 44, 3},
    {44, 174, -1, 18, 2},
    {52, 175, -1, 23, 2},
    {70, 176, 1, 24, 3},
    {88, 177, -1, 25, 2},
    {106, 178, 2, 26, 3},
    {124, 179, -1, 45, 2},
    {128, 180, -1, 16, 2},
    {136, 181, 3, 27, 3},
    {140, 182, 4, 46, 3},
    {0, 189, -1, 29, 2},
    {2, 190, -1, 30, 2},
    {4, 191, -1, 47, 2},
    {12, 192, -1, 42, 2},
    {48, 193, -1, 48, 2},
    {2, 194, -1, 49, 2},
    {4, 195, -1, 20, 2},
    {8, 196, -1, 21, 2},
    {16, 197, 0, 50, 3},
    {28, 198, -1, 51, 2},
    {32, 199, -1, 52, 2},
    {52, 200, 1, 53, 3},
    {64, 201, 2, 54, 3},
    {68, 202, 3, 28, 3},
    {0, 203, -1, 29, 2},
    {2, 204, -1, 30, 2},
    {4, 205, -1, 17, 2},
    {2, 206, -1, 52, 2},
    {20, 207, -1, 51, 2},
    {24, 208, 0, 53, 3},
    {36, 209, 1, 54, 3},
    {0, 217, -1, 29, 2},
    {2, 218, -1, 30, 2},
    {4, 219, -1, 55, 2},
    {68, 220, -1, 50, 2},
    {0, 221, -1, 29, 2},
    {2, 222, -1, 30, 2},
    {4, 223, -1, 17, 2},
    {4, 224, -1, 56, 2},
    {12, 225, 0, 57, 3},
    {32, 226, 1, 58, 3},
    {36, 227, 2, 54, 3},
    {40, 228, -1, 59, 2},
    {52, 229, 3, 60, 3},
    {0, 230, -1, 29, 2},
    {2, 231, -1, 30, 2},
    {4, 232, -1, 61, 2},
    {8, 233, -1, 17, 2},
    {4, 246, -1, 62, 2},
    {8, 247, 0, 37, 3},
    {12, 248, 1, 57, 3},
    {32, 249, 2, 58, 3},
    {36, 250, 3, 59, 3},
    {48, 251, 4, 60, 3},
    {2, 252, -1, 29, 2},
    {4, 253, -1, 30, 2},
    {6, 254, 0, 52, 3},
    {24, 255, 1, 51, 3},
    {28, 256, -1, 63, 2},
    {48, 257, -1, 64, 2},
    {52, 258, -1, 65, 2},
    {56, 259, -1, 20, 3},
    {60, 260, 2, 21, 3},
    {68, 261, -1, 15, 2},
    {72, 262, -1, 16, 2},
    {80, 263, -1, 66, 3},
    {84, 264, 3, 67, 3},
    {4, 115, -1, 38, 2},
    {8, 116, 0, 68, 3},
    {12, 117, -1, 69, 2},
    {2, 268, -1, 70, 2},
    {20, 269, 0, 71, 3},
    {4, 277, -1, 72, 2},
    {16, 278, -1, 73, 3},
    {20, 279, 0, 74, 3},
    {28, 280, -1, 75, 2},
    {0, 281, -1, 76, 2},
    {4, 282, -1, 75, 2},
    {4, 283, -1, 77, 2},
    {12, 284, 0, 78, 3},
    {20, 285, -1, 79, 3},
    {4, 290, -1, 80, 2},
    {12, 291, 0, 81, 3},
    {16, 292, 1, 82, 3},
    {4, 303, -1, 83, 2},
    {44, 304, 0, 84, 3},
    {72, 305, 1, 85, 3},
    {76, 306, 2, 86, 3},
    {0, 307, -1, 15, 2},
    {4, 308, -1, 87, 2},
    {4, 312, -1, 88, 2},
    {4, 313, -1, 89, 2},
    {4, 314, -1, 90, 2},
    {12, 315, -1, 37, 2},
    {16, 316, 0, 91, 3},
    {0, 317, -1, 92, 2},
    {12, 318, -1, 93, 2},
    {0, 319, -1, 94, 2},
    {8, 321, -1, 95, 2},
    {4, 323, -1, 96, 2},
    {4, 324, -1, 97, 2},
    {4, 325, -1, 98, 2},
    {4, 326, -1, 99, 2},
    {4, 327, -1, 100, 2},
    {4, 328, -1, 96, 2},
    {4, 329, -1, 97, 2},
    {4, 330, -1, 98, 2},
    {4, 331, -1, 99, 2},
    {4, 332, -1, 100, 2},
    {4, 333, -1, 96, 2},
    {4, 334, -1, 97, 2},
    {4, 335, -1, 98, 2},
    {4, 336, -1, 99, 2},
    {4, 337, -1, 100, 2},
    {4, 338, -1, 96, 2},
    {4, 339, -1, 97, 2},
    {4, 340, -1, 98, 2},
    {4, 341, -1, 99, 2},
    {4, 342, -1, 100, 2},
    {4, 343, -1, 96, 2},
    {4, 344, -1, 97, 2},
    {4, 345, -1, 98, 2},
    {4, 346, -1, 99, 2},
    {4, 347, -1, 100, 2},
    {4, 348, -1, 96, 2},
    {4, 349, -1, 97, 2},
    {4, 350, -1, 98, 2},
    {4, 351, -1, 99, 2},
    {4, 352, -1, 100, 2},
    {4, 353, -1, 96, 2},
    {4, 354, -1, 97, 2},
    {4, 355, -1, 98, 2},
    {4, 356, -1, 99, 2},
    {4, 357, -1, 100, 2},
    {4, 358, -1, 96, 2},
    {4, 359, -1, 97, 2},
    {4, 360, -1, 98, 2},
    {4, 361, -1, 99, 2},
    {4, 362, -1, 100, 2},
    {4, 366, -1, 96, 2},
    {4, 367, -1, 97, 2},
    {4, 368, -1, 98, 2},
    {4, 369, -1, 99, 2},
    {4, 370, -1, 100, 2},
    {0, 382, -1, 101, 2},
    {136, 300, -1, 102, 2},
    {156, 301, -1, 103, 2},
    {0, 390, -1, 104, 2},
    {84, 300, -1, 102, 2},
    {104, 301, -1, 103, 2},
    {4, 417, -1, 105, 2},
    {268, 423, 0, 106, 3},
    {272, 427, 1, 107, 3},
    {1, 428, -1, 108, 2},
    {42, 429, 0, 109, 3},
    {59, 430, 1, 110, 3},
    {65, 431, 2, 111, 3},
    {2, 433, -1, 112, 2},
    {2, 434, -1, 113, 2},
    {2, 435, -1, 114, 2},
    {2, 436, -1, 115, 2},
    {1, 437, 0, 116, 3},
    {32, 438, 1, 117, 3},
    {4, 441, 0, 118, 3},
    {8, 442, 1, 117, 3},
    {4, 450, -1, 119, 2},
    {4, 451, -1, 120, 2},
    {0, 461, -1, 83, 2},
    {0, 462, -1, 92, 2},
    {12, 463, -1, 37, 2},
    {0, 464, -1, 121, 2},
    {8, 465, -1, 122, 2},
    {12, 466, -1, 50, 2},
    {24, 467, -1, 123, 2},
    {0, 474, -1, 124, 2},
    {36, 475, -1, 125, 2},
    {0, 114, -1, 126, 34},
    {0, 476, -1, 127, 2},
    {0, 477, -1, 128, 2},
    {4, 478, -1, 129, 2},
    {0, 99, -1, 130, 2},
    {4, 100, -1, 131, 2},
    {0, 103, -1, 132, 2},
    {4, 104, -1, 133, 2},
    {0, 107, -1, 134, 2},
    {4, 108, -1, 135, 2},
    {0, 111, -1, 136, 2},
    {4, 112, -1, 137, 2},
    {0, 119, -1, 138, 2},
    {4, 120, -1, 139, 2},
    {0, 122, -1, 140, 2},
    {4, 123, -1, 125, 2},
    {0, 130, -1, 141, 2},
    {4, 131, -1, 142, 2},
    {0, 184, -1, 143, 2},
    {4, 185, -1, 144, 2},
    {4, 210, -1, 56, 2},
    {12, 211, 0, 57, 3},
    {32, 212, 1, 58, 3},
    {36, 213, 2, 54, 3},
    {40, 214, -1, 59, 2},
    {52, 215, 3, 60, 3},
    {4, 234, -1, 19, 2},
    {16, 235, -1, 145, 3},
    {20, 236, 0, 146, 3},
    {28, 237, 1, 18, 3},
    {36, 238, 2, 23, 3},
    {54, 239, 3, 24, 3},
    {72, 240, 4, 25, 3},
    {90, 241, 5, 26, 3},
    {108, 242, -1, 45, 3},
    {112, 243, 6, 16, 3},
    {120, 244, 7, 27, 3},
    {4, 265, -1, 147, 2},
    {8, 266, 0, 148, 3},
    {4, 270, -1, 38, 2},
    {8, 271, 0, 149, 3},
    {4, 273, -1, 38, 2},
    {8, 274, -1, 149, 3},
    {12, 275, 0, 150, 3},
    {4, 286, 0, 151, 3},
    {12, 287, 1, 152, 3},
    {20, 288, 2, 153, 3},
    {4, 294, -1, 51, 2},
    {8, 295, -1, 52, 2},
    {28, 296, -1, 37, 2},
    {32, 297, 0, 154, 3},
    {4, 0, -1, 155, 2},
    {12, 299, 0, 156, 3},
    {0, 300, -1, 155, 2},
    {20, 301, -1, 90, 2},
    {4, 309, -1, 157, 2},
    {12, 310, 0, 158, 3},
    {0, 319, -1, 94, 2},
    {8, 320, -1, 159, 2},
    {4, 364, -1, 160, 2},
    {2, 373, -1, 161, 2},
    {2, 374, -1, 162, 2},
    {0, 375, -1, 163, 2},
    {20, 375, -1, 164, 2},
    {4, 378, 0, 165, 7},
    {8, 372, -1, 167, 2},
    {12, 300, -1, 103, 2},
    {32, 363, -1, 168, 2},
    {40, 376, -1, 169, 2},
    {80, 363, -1, 170, 2},
    {88, 302, -1, 171, 2},
    {116, 379, 1, 172, 3},
    {124, 380, 2, 173, 3},
    {132, 381, 3, 174, 3},
    {4, 0, -1, 175, 2},
    {12, 383, 0, 176, 7},
    {16, 384, -1, 178, 2},
    {4, 372, -1, 179, 2},
    {8, 375, -1, 180, 2},
    {28, 386, 0, 181, 3},
    {4, 371, 0, 182, 3},
    {8, 300, -1, 103, 2},
    {28, 363, -1, 168, 2},
    {36, 375, -1, 183, 2},
    {56, 375, 1, 184, 3},
    {76, 388, 2, 185, 3},
    {80, 389, 3, 186, 3},
    {2, 391, -1, 112, 2},
    {2, 392, -1, 113, 2},
    {2, 394, -1, 187, 2},
    {2, 395, -1, 188, 2},
    {2, 400, -1, 187, 2},
    {2, 401, -1, 188, 2},
    {1, 405, -1, 108, 2},
    {42, 406, 0, 109, 3},
    {59, 407, 1, 110, 3},
    {65, 408, 2, 111, 3},
    {2, 393, 0, 189, 3},
    {8, 396, 1, 190, 3},
    {28, 410, 2, 191, 3},
    {45, 411, 3, 192, 3},
    {70, 412, 4, 193, 3},
    {90, 413, 5, 194, 3},
    {155, 414, 6, 195, 3},
    {188, 415, 7, 196, 3},
    {260, 416, 8, 197, 3},
    {0, 420, -1, 94, 2},
    {9, 421, -1, 159, 2},
    {0, 424, -1, 198, 2},
    {4, 425, -1, 199, 2},
    {4, 443, 0, 200, 3},
    {12, 444, 1, 201, 3},
    {20, 445, 2, 202, 3},
    {28, 446, -1, 203, 2},
    {1, 448, -1, 204, 2},
    {17, 449, 0, 205, 3},
    {0, 452, -1, 94, 2},
    {9, 453, -1, 159, 2},
    {0, 455, -1, 206, 2},
    {8, 456, -1, 207, 2},
    {12, 457, -1, 51, 2},
    {16, 458, -1, 52, 2},
    {36, 459, -1, 37, 2},
    {4, 468, -1, 37, 2},
    {8, 469, 0, 21, 3},
    {16, 470, -1, 20, 2},
    {20, 471, 1, 208, 3},
    {28, 472, 2, 209, 3}
};

#ifdef OSS_SPARTAN_AWARE
#if ((OSS_SPARTAN_AWARE + 0) > 12)
typedef struct ExtParms {
    int           versId;
    const void    *xparm[7];
} ExtParms;
static ExtParms const extParms = {
    OSS_COMPILER_API_LEVEL,
    {NULL, NULL, NULL, NULL, NULL, NULL, (char *)NULL + 4}
};
#endif /* OSS_SPARTAN_AWARE  > 12 */
#endif /* OSS_SPARTAN_AWARE */

static void * const _enamearray[] = {
    NULL,
    (char *)NULL + 0x6, (void *)_v327,
    (void *)"telex", (void *)"teletex", (void *)"g3-facsimile", (void *)"g4-facsimile", (void *)"ia5-terminal",
    (void *)"videotex",
    (char *)NULL + 0x3, (void *)_v328,
    (void *)"v1", (void *)"v2", (void *)"v3",
    (void *)"tkt-vno",
    (void *)"realm",
    (void *)"sname",
    (void *)"enc-part",
    (void *)"flags",
    (void *)"key",
    (void *)"crealm",
    (void *)"cname",
    (void *)"transited",
    (void *)"authtime",
    (void *)"starttime",
    (void *)"endtime",
    (void *)"renew-till",
    (void *)"caddr",
    (void *)"authorization-data",
    (void *)"pvno",
    (void *)"msg-type",
    (void *)"padata",
    (void *)"req-body",
    (void *)"kdc-options",
    (void *)"from",
    (void *)"till",
    (void *)"rtime",
    (void *)"nonce",
    (void *)"etype",
    (void *)"addresses",
    (void *)"enc-authorization-data",
    (void *)"additional-tickets",
    (void *)"ticket",
    (void *)"last-req",
    (void *)"key-expiration",
    (void *)"srealm",
    (void *)"encrypted-pa-data",
    (void *)"ap-options",
    (void *)"authenticator",
    (void *)"authenticator-vno",
    (void *)"cksum",
    (void *)"cusec",
    (void *)"ctime",
    (void *)"subkey",
    (void *)"seq-number",
    (void *)"safe-body",
    (void *)"user-data",
    (void *)"timestamp",
    (void *)"usec",
    (void *)"s-address",
    (void *)"r-address",
    (void *)"tickets",
    (void *)"ticket-info",
    (void *)"stime",
    (void *)"susec",
    (void *)"error-code",
    (void *)"e-text",
    (void *)"e-data",
    (void *)"kvno",
    (void *)"cipher",
    (void *)"patimestamp",
    (void *)"pausec",
    (void *)"ad-checksum",
    (void *)"i-realm",
    (void *)"i-sname",
    (void *)"elements",
    (void *)"condition-count",
    (void *)"newpasswd",
    (void *)"targname",
    (void *)"targrealm",
    (void *)"signedAuthPack",
    (void *)"trustedCertifiers",
    (void *)"kdcPkId",
    (void *)"pkAuthenticator",
    (void *)"clientPublicValue",
    (void *)"supportedCMSTypes",
    (void *)"clientDHNonce",
    (void *)"principalName",
    (void *)"dhInfo",
    (void *)"encKeyPack",
    (void *)"subjectPublicKey",
    (void *)"dhKeyExpiration",
    (void *)"replyKey",
    (void *)"asChecksum",
    (void *)"type",
    (void *)"values",
    (void *)"teletexString",
    (void *)"printableString",
    (void *)"universalString",
    (void *)"utf8String",
    (void *)"bmpString",
    (void *)"tbsCertificate",
    (void *)"signatureAlgorithm",
    (void *)"signature",
    (void *)"tbsCertList",
    (void *)"built-in-standard-attributes",
    (void *)"built-in-domain-defined-attributes",
    (void *)"extension-attributes",
    (void *)"surname",
    (void *)"given-name",
    (void *)"initials",
    (void *)"generation-qualifier",
    (void *)"x121-dcc-code",
    (void *)"iso-3166-alpha2-code",
    (void *)"numeric-code",
    (void *)"printable-code",
    (void *)"printable-string",
    (void *)"teletex-string",
    (void *)"printable-address",
    (void *)"e163-4-address",
    (void *)"psap-address",
    (void *)"userName",
    (void *)"userRealm",
    (void *)"auth-package",
    (void *)"user-id",
    (void *)"checksum",
    (void *)"kerberosFlags",
    (void *)"include-pac",
    (void *)"restriction-type",
    (void *)"restriction",
    (void *)"name-type",
    (void *)"name-string",
    (void *)"addr-type",
    (void *)"address",
    (void *)"ad-type",
    (void *)"ad-data",
    (void *)"padata-type",
    (void *)"padata-value",
    (void *)"keytype",
    (void *)"keyvalue",
    (void *)"cksumtype",
    (void *)"tr-type",
    (void *)"contents",
    (void *)"lr-type",
    (void *)"lr-value",
    (void *)"prealm",
    (void *)"pname",
    (void *)"data-type",
    (void *)"data-value",
    (void *)"salt",
    (void *)"s2kparams",
    (void *)"subjectName",
    (void *)"issuerAndSerialNumber",
    (void *)"subjectKeyIdentifier",
    (void *)"paChecksum",
    (void *)"algorithm",
    (void *)"parameters",
    (void *)"dhSignedData",
    (void *)"serverDHNonce",
    (void *)"value",
    (void *)"rdnSequence",
    (void *)"utcTime",
    (void *)"generalTime",
    (void *)"notBefore",
    (void *)"notAfter",
    (void *)"version", (void *)&_v39,
    (void *)"serialNumber",
    (void *)"issuer",
    (void *)"validity",
    (void *)"subject",
    (void *)"subjectPublicKeyInfo",
    (void *)"issuerUniqueID",
    (void *)"subjectUniqueID",
    (void *)"extensions",
    (void *)"extnID",
    (void *)"critical", (void *)&_v38,
    (void *)"extnValue",
    (void *)"userCertificate",
    (void *)"revocationDate",
    (void *)"crlEntryExtensions",
    (void *)"version",
    (void *)"thisUpdate",
    (void *)"nextUpdate",
    (void *)"revokedCertificates",
    (void *)"crlExtensions",
    (void *)"numeric",
    (void *)"printable",
    (void *)"country-name",
    (void *)"administration-domain-name",
    (void *)"network-address",
    (void *)"terminal-identifier",
    (void *)"private-domain-name",
    (void *)"organization-name",
    (void *)"numeric-user-identifier",
    (void *)"personal-name",
    (void *)"organizational-unit-names",
    (void *)"extension-attribute-type",
    (void *)"extension-attribute-value",
    (void *)"pSelector",
    (void *)"sSelector",
    (void *)"tSelector",
    (void *)"nAddresses",
    (void *)"number",
    (void *)"sub-address",
    (void *)"kdc-name",
    (void *)"kdc-realm",
    (void *)"subject-certificate",
    (void *)"options"
};

static const Etag _tagarray[] = {
    1, 0x0006, 2, 0x4001, 0x0010, 9, 12, 15, 18, 1,
    0x8000, 1, 1, 0x8001, 2, 1, 0x8002, 3, 1, 0x8003,
    4, 2, 0x4003, 0x0010, 35, 38, 41, 44, 47, 50,
    53, 58, 61, 68, 73, 1, 0x8000, 1, 1, 0x8001,
    2, 1, 0x8002, 3, 1, 0x8003, 4, 1, 0x8004, 5,
    1, 0x8005, 6, 2, 0x8006, 7, 0x8007, 8, 1, 0x8007,
    8, 3, 0x8008, 9, 0x8009, 10, 0x800a, 11, 2, 0x8009,
    10, 0x800a, 11, 1, 0x800a, 11, 2, 0x400a, 0x0010, 83,
    86, 89, 94, 1, 0x8001, 1, 1, 0x8002, 2, 2,
    0x8003, 3, 0x8004, 4, 1, 0x8004, 4, 2, 0x400c, 0x0010,
    1, 0x0010, 114, 117, 122, 125, 132, 137, 140, 145,
    148, 151, 158, 163, 1, 0x8000, 1, 2, 0x8001, 2,
    0x8002, 3, 1, 0x8002, 3, 3, 0x8003, 4, 0x8004, 5,
    0x8005, 6, 2, 0x8004, 5, 0x8005, 6, 1, 0x8005, 6,
    2, 0x8006, 7, 0x8007, 8, 1, 0x8007, 8, 1, 0x8008,
    9, 3, 0x8009, 10, 0x800a, 11, 0x800b, 12, 2, 0x800a,
    11, 0x800b, 12, 1, 0x800b, 12, 2, 0x400b, 0x0010, 176,
    179, 182, 187, 190, 193, 196, 1, 0x8000, 1, 1,
    0x8001, 2, 2, 0x8002, 3, 0x8003, 4, 1, 0x8003, 4,
    1, 0x8004, 5, 1, 0x8005, 6, 1, 0x8006, 7, 2,
    0x400d, 0x0010, 2, 0x4019, 0x0010, 218, 221, 224, 227, 232,
    235, 238, 243, 246, 251, 254, 257, 262, 1, 0x8000,
    1, 1, 0x8001, 2, 1, 0x8002, 3, 2, 0x8003, 4,
    0x8004, 5, 1, 0x8004, 5, 1, 0x8005, 6, 2, 0x8006,
    7, 0x8007, 8, 1, 0x8007, 8, 2, 0x8008, 9, 0x8009,
    10, 1, 0x8009, 10, 1, 0x800a, 11, 2, 0x800b, 12,
    0x800c, 13, 1, 0x800c, 13, 2, 0x401a, 0x0010, 2, 0x400e,
    0x0010, 276, 279, 282, 285, 288, 1, 0x8000, 1, 1,
    0x8001, 2, 1, 0x8002, 3, 1, 0x8003, 4, 1, 0x8004,
    5, 2, 0x4002, 0x0010, 303, 306, 309, 312, 317, 320,
    323, 330, 335, 1, 0x8000, 1, 1, 0x8001, 2, 1,
    0x8002, 3, 2, 0x8003, 4, 0x8004, 5, 1, 0x8004, 5,
    1, 0x8005, 6, 3, 0x8006, 7, 0x8007, 8, 0x8008, 9,
    2, 0x8007, 8, 0x8008, 9, 1, 0x8008, 9, 2, 0x400f,
    0x0010, 344, 347, 350, 1, 0x8000, 1, 1, 0x8001, 2,
    1, 0x8002, 3, 2, 0x401b, 0x0010, 360, 363, 366, 371,
    1, 0x8000, 1, 1, 0x8001, 2, 2, 0x8002, 3, 0x8003,
    4, 1, 0x8003, 4, 2, 0x4014, 0x0010, 2, 0x4015, 0x0010,
    383, 386, 389, 1, 0x8000, 1, 1, 0x8001, 2, 1,
    0x8003, 3, 2, 0x401c, 0x0010, 401, 404, 413, 420, 425,
    428, 1, 0x8000, 1, 4, 0x8001, 2, 0x8002, 3, 0x8003,
    4, 0x8004, 5, 3, 0x8002, 3, 0x8003, 4, 0x8004, 5,
    2, 0x8003, 4, 0x8004, 5, 1, 0x8004, 5, 1, 0x8005,
    6, 2, 0x4016, 0x0010, 2, 0x401d, 0x0010, 443, 446, 457,
    466, 473, 478, 1, 0x8000, 1, 5, 0x8001, 2, 0x8002,
    3, 0x8003, 4, 0x8004, 5, 0x8005, 6, 4, 0x8002, 3,
    0x8003, 4, 0x8004, 5, 0x8005, 6, 3, 0x8003, 4, 0x8004,
    5, 0x8005, 6, 2, 0x8004, 5, 0x8005, 6, 1, 0x8005,
    6, 2, 0x401e, 0x0010, 497, 500, 503, 510, 515, 518,
    521, 524, 531, 536, 539, 542, 547, 1, 0x8000, 1,
    1, 0x8001, 2, 3, 0x8002, 3, 0x8003, 4, 0x8004, 5,
    2, 0x8003, 4, 0x8004, 5, 1, 0x8004, 5, 1, 0x8005,
    6, 1, 0x8006, 7, 3, 0x8007, 8, 0x8008, 9, 0x8009,
    10, 2, 0x8008, 9, 0x8009, 10, 1, 0x8009, 10, 1,
    0x800a, 11, 2, 0x800b, 12, 0x800c, 13, 1, 0x800c, 13,
    553, 556, 561, 1, 0x8000, 1, 2, 0x8001, 2, 0x8002,
    3, 1, 0x8002, 3, 566, 569, 1, 0x8000, 1, 1,
    0x8001, 2, 576, 579, 586, 591, 1, 0x8000, 1, 3,
    0x8001, 2, 0x8002, 3, 0x8003, 4, 2, 0x8002, 3, 0x8003,
    4, 1, 0x8003, 4, 0, 3, 0x0000, 0, 0x8000, 1,
    0x8001, 2, 604, 607, 1, 0x0006, 1, 1, 0x0011, 2,
    5, 0x000c, 4, 0x0013, 2, 0x0014, 1, 0x001c, 3, 0x001e,
    5, 1, 0x0013, 1, 0x0016, 628, 631, 634, 1, 0x0010,
    1, 1, 0x0010, 2, 1, 0x0003, 3, 640, 643, 648,
    1, 0x0010, 1, 2, 0x0010, 2, 0x0011, 3, 1, 0x0011,
    3, 1, 0x0014, 1, 0x0011, 4, 0x8000, 1, 0x8001, 2,
    0x8002, 3, 0x8003, 4, 2, 0x0012, 1, 0x0013, 2, 2,
    0x0013, 1, 0x0014, 2, 2, 0x0010, 1, 0x0014, 2, 2,
    0x0010, 1, 0x8000, 2, 1, 0x0002, 687, 1, 0x8000, 1,
    691, 1, 0x0003, 1, 1, 0x0004, 1, 0x001b, 2, 0x8000,
    0x0002, 2, 0x8001, 0x0010, 1, 0x0018, 2, 0x8001, 0x0004, 2,
    0x8001, 0x0002, 2, 0x8002, 0x0004, 717, 720, 1, 0x8001, 1,
    1, 0x8002, 2, 1, 0x0003, 2, 0x8001, 0x001b, 2, 0x8002,
    0x0010, 2, 0x8003, 0x0010, 2, 0x8000, 0x0003, 2, 0x8002, 0x001b,
    2, 0x8004, 0x0010, 2, 0x8005, 0x0018, 2, 0x8006, 0x0018, 2,
    0x8007, 0x0018, 2, 0x8008, 0x0018, 2, 0x8009, 0x0010, 2, 0x800a,
    0x0010, 2, 0x8004, 0x0018, 2, 0x8007, 0x0002, 2, 0x8008, 0x0010,
    2, 0x800b, 0x0010, 2, 0x8002, 0x0002, 2, 0x8003, 0x001b, 3,
    0x8005, 0x4001, 0x0010, 2, 0x8006, 0x0010, 2, 0x8000, 0x0010, 2,
    0x8003, 0x0018, 2, 0x8004, 0x0003, 2, 0x8009, 0x001b, 2, 0x800c,
    0x0010, 2, 0x8001, 0x0018, 2, 0x8002, 0x0003, 3, 0x8003, 0x4001,
    0x0010, 2, 0x8004, 0x0002, 2, 0x8000, 0x0018, 2, 0x8003, 0x0002,
    2, 0x8000, 0x0004, 2, 0x8005, 0x0010, 2, 0x8003, 0x0003, 2,
    0x8008, 0x001b, 843, 846, 867, 886, 903, 918, 931, 942,
    951, 958, 963, 1, 0x8000, 1, 10, 0x8001, 2, 0x8002,
    3, 0x8003, 4, 0x8004, 5, 0x8005, 6, 0x8006, 7, 0x8007,
    8, 0x8008, 9, 0x8009, 10, 0x800a, 11, 9, 0x8002, 3,
    0x8003, 4, 0x8004, 5, 0x8005, 6, 0x8006, 7, 0x8007, 8,
    0x8008, 9, 0x8009, 10, 0x800a, 11, 8, 0x8003, 4, 0x8004,
    5, 0x8005, 6, 0x8006, 7, 0x8007, 8, 0x8008, 9, 0x8009,
    10, 0x800a, 11, 7, 0x8004, 5, 0x8005, 6, 0x8006, 7,
    0x8007, 8, 0x8008, 9, 0x8009, 10, 0x800a, 11, 6, 0x8005,
    6, 0x8006, 7, 0x8007, 8, 0x8008, 9, 0x8009, 10, 0x800a,
    11, 5, 0x8006, 7, 0x8007, 8, 0x8008, 9, 0x8009, 10,
    0x800a, 11, 4, 0x8007, 8, 0x8008, 9, 0x8009, 10, 0x800a,
    11, 3, 0x8008, 9, 0x8009, 10, 0x800a, 11, 2, 0x8009,
    10, 0x800a, 11, 1, 0x800a, 11, 2, 0x8002, 0x0018, 2,
    0x8005, 0x0002, 2, 0x8006, 0x0002, 2, 0x8007, 0x001b, 2, 0x800b,
    0x001b, 2, 0x800c, 0x0004, 1, 0x8000, 1, 0x8001, 1, 0x8002,
    993, 1000, 1005, 3, 0x8000, 1, 0x8001, 2, 0x8002, 3,
    2, 0x8001, 2, 0x8002, 3, 1, 0x8002, 3, 2, 0x8003,
    0x0004, 1013, 1016, 1, 0x0006, 1, 0, 1019, 1022, 1,
    0x0010, 1, 1, 0x0003, 2, 2, 0x8000, 0x001b, 1, 0x001c,
    1, 0x000c, 1, 0x001e, 1, 0x0010, 1, 1, 0x0017, 2,
    0x0017, 1, 0x0018, 2, 1046, 1051, 2, 0x0017, 1, 0x0018,
    1, 2, 0x0017, 2, 0x0018, 2, 1066, 1071, 1074, 1077,
    1080, 1083, 1086, 1089, 1096, 1101, 2, 0x0002, 2, 0x8000,
    1, 1, 0x0002, 2, 1, 0x0010, 3, 1, 0x0010, 4,
    1, 0x0010, 5, 1, 0x0010, 6, 1, 0x0010, 7, 3,
    0x8001, 8, 0x8002, 9, 0x8003, 10, 2, 0x8002, 9, 0x8003,
    10, 1, 0x8003, 10, 1, 0x0001, 1109, 1112, 1117, 1,
    0x0006, 1, 2, 0x0001, 2, 0x0004, 3, 1, 0x0004, 3,
    1123, 1126, 1131, 1, 0x0002, 1, 2, 0x0017, 2, 0x0018,
    2, 1, 0x0010, 3, 1141, 1146, 1149, 1152, 1157, 1166,
    1171, 2, 0x0002, 1, 0x0010, 2, 1, 0x0010, 2, 1,
    0x0010, 3, 2, 0x0017, 4, 0x0018, 4, 4, 0x0010, 6,
    0x0017, 5, 0x0018, 5, 0x8000, 7, 2, 0x0010, 6, 0x8000,
    7, 1, 0x8000, 7, 1, 0x0012, 1, 0x4001, 1, 0x4002,
    1, 0x8003, 1, 0x8004, 1, 0x8005, 1, 0x8006, 1197, 1216,
    1233, 1248, 1261, 1272, 1281, 1288, 1293, 9, 0x4001, 1,
    0x4002, 2, 0x8000, 3, 0x8001, 4, 0x8002, 5, 0x8003, 6,
    0x8004, 7, 0x8005, 8, 0x8006, 9, 8, 0x4002, 2, 0x8000,
    3, 0x8001, 4, 0x8002, 5, 0x8003, 6, 0x8004, 7, 0x8005,
    8, 0x8006, 9, 7, 0x8000, 3, 0x8001, 4, 0x8002, 5,
    0x8003, 6, 0x8004, 7, 0x8005, 8, 0x8006, 9, 6, 0x8001,
    4, 0x8002, 5, 0x8003, 6, 0x8004, 7, 0x8005, 8, 0x8006,
    9, 5, 0x8002, 5, 0x8003, 6, 0x8004, 7, 0x8005, 8,
    0x8006, 9, 4, 0x8003, 6, 0x8004, 7, 0x8005, 8, 0x8006,
    9, 3, 0x8004, 7, 0x8005, 8, 0x8006, 9, 2, 0x8005,
    8, 0x8006, 9, 1, 0x8006, 9, 1298, 1301, 1, 0x0013,
    1, 1, 0x0013, 2, 2, 0x8003, 0x0011, 1311, 1320, 1327,
    1332, 4, 0x8000, 1, 0x8001, 2, 0x8002, 3, 0x8003, 4,
    3, 0x8001, 2, 0x8002, 3, 0x8003, 4, 2, 0x8002, 3,
    0x8003, 4, 1, 0x8003, 4, 1337, 1340, 1, 0x0014, 1,
    1, 0x0014, 2, 1348, 1351, 1356, 1359, 1364, 1, 0x8000,
    1, 2, 0x8001, 2, 0x8002, 3, 1, 0x8002, 3, 2,
    0x8003, 4, 0x8004, 5, 1, 0x8004, 5, 2, 0x8000, 0x0001
};


#ifdef OSS_SPARTAN_AWARE
#if ((OSS_SPARTAN_AWARE + 0) >= 3)
static void _oss_post_init(struct ossGlobal *world) {
    static const unsigned char _oss_typeinfo[] = {
        0x00, 0x77, 0x34, 0xf6, 0x58, 0xe1, 0xee, 0x8b, 0xab, 0x91,
        0xea, 0x89, 0xab, 0x92, 0xea, 0x90, 0x33, 0xd5, 0x96, 0x38,
        0xf7, 0xdb, 0x92, 0x6f, 0x65, 0x02, 0x80, 0xd2, 0x74, 0xc0,
        0x68, 0x81, 0xfe, 0x72, 0xca, 0xc8, 0x41, 0x20, 0xb5, 0x9b,
        0x3e, 0xc4, 0xa4, 0x1c, 0x10, 0x9d, 0x95, 0x4a, 0xeb, 0xac,
        0x7b, 0xfc, 0x91, 0x4b, 0x2c, 0x07, 0x21, 0x6f, 0xe8, 0xfe,
        0x03, 0x8a, 0x57, 0x2f, 0xa7, 0xb0, 0xa5, 0xb7, 0x54, 0xdb,
        0xed, 0x39, 0x25, 0xaa, 0x60, 0x70, 0xe0, 0xb4, 0x9d, 0x4f,
        0xf1, 0x76, 0x76, 0x8c, 0x61, 0x90, 0x22, 0x54, 0xde, 0xc2,
        0x5d, 0x17, 0x93, 0xcf, 0xec, 0xfa, 0x96, 0x21, 0xaf, 0xa7,
        0x7a, 0xda, 0x98, 0x4b, 0xcc, 0xa6, 0xd2, 0x51, 0xf4, 0xb8,
        0x1f, 0xec, 0xfc, 0x03, 0x13, 0x54, 0x2f, 0x5f, 0xa8, 0xce,
        0x81
    };
    ossInitRootContext1(world, (unsigned char *)_oss_typeinfo);
#ifdef OSS_SPARTAN_AWARE
#if ((OSS_SPARTAN_AWARE + 0) > 12)
    ossSetExtParms(world, (void *)&extParms);
#endif /* OSS_SPARTAN_AWARE  > 12 */
#endif /* OSS_SPARTAN_AWARE */
}
#endif /* OSS_SPARTAN_AWARE >= 3 */
#endif /* OSS_SPARTAN_AWARE */

static const struct eheader _head = {_ossinit_kekeo_asn1, -1, 115, 2901, 91, 479,
    (unsigned short *)_pduarray, (struct etype *)_etypearray,
    (struct efield *)_efieldarray, (void **)_enamearray, (Etag *)_tagarray,
    (struct ConstraintEntry *)_econstraintarray, NULL, NULL, 0, NULL, 0};

#ifdef _OSSGETHEADER
void *DLL_ENTRY_FDEF ossGetHeader()
{
    return (void *)&_head;
}
#endif /* _OSSGETHEADER */

void * const kekeo_asn1 = (void *)&_head;
